---
title: "Pulmonary Exacerbations in CF"
author: "Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
    theme:
      light: flatly
      dark: darkly
bibliography: /Users/timvigers/Documents/Miscellaneous/zotero.bib
csl: /Users/timvigers/Documents/Miscellaneous/american-medical-association.csl
editor: source
---

```{r setup}
#| include: false
library(tidyverse)
library(lubridate)
library(gtsummary)
knitr::opts_knit$set(root.dir = "/Users/timvigers/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Vigers/CF/Scott Sagel/PEx in CF")
```

```{r data cleaning}
# Import
df <- read.csv("./Data_Raw/ExacerbationsInCF222_DATA_2024-01-02_0857.csv",
  na.strings = ""
)
# Get admit year (some missing in admit_year field)
df$year <- year(df$admit_date)
# Rename centers
df$redcap_data_access_group <- factor(df$redcap_data_access_group,
  levels = c("chco", "childrens_national", "orange_county", "rady", "seattle"),
  labels = c("CHCO", "Children's National", "Orange County", "Rady", "Seattle")
)
# CFTR modulators
df$cftr_mod <- factor(df$cftr_mod, levels = 0:1, labels = c("No", "Yes"))
df$cftr_mod_spec <- factor(df$cftr_mod_spec,
  levels = 1:4, labels = c("Kalydeco", "Orkambi", "Symdeko", "Trikafta")
)
df$Trikafta <- factor(df$cftr_mod_spec == "Trikafta",
  levels = c(F, T), labels = c("No", "Yes")
)
# Labels
labels <- list(
  "Aspergillus fumigatus" = "fungi___1",
  "Aspergillus (other species)" = "fungi___2",
  "Scedosporium apiospermum" = "fungi___3",
  "Candidia (any species)" = "fungi___4",
  "Other fungus" = "fungi___5",
  "NTM testing performed?" = "ntm_test",
  "M. abscessus species" = "ntm___1",
  "M. avium complex species" = "ntm___2",
  "Other NTM species" = "ntm___3",
  "A. xylosoxidans" = "admit_cx_results___1",
  "B. cepacia complex" = "admit_cx_results___2",
  "H. influenzae" = "admit_cx_results___3",
  "MRSA" = "admit_cx_results___4",
  "Methicillin-susceptible Staph aureus" = "admit_cx_results___5",
  "P. aeruginosa" = "admit_cx_results___6",
  "P. aeruginosa mucoid" = "admit_cx_results___7",
  "S. maltophilia" = "admit_cx_results___8",
  "Other bacteria" = "admit_cx_results___9",
  "On CFTR Modulator?" = "cftr_mod",
  "CFTR Modulator Type" = "cftr_mod_spec",
  "Cultures Tested" = "redcap_data_access_group"
)
labels <- setNames(names(labels), labels)
# Format
df <- df %>%
  select(
    sid, redcap_event_name, redcap_data_access_group, year, cftr_mod,
    cftr_mod_spec, Trikafta, fungal_test, fungi___1:fungi___5,
    ntm_test, ntm___1:ntm___3,
    admit_cx_results___1:admit_cx_results___9
  ) %>%
  filter(!is.na(year))
```

# Fungi

The tables below are limited to patients who had fungal testing performed.

```{r}
#| label: tbl-fungi
#| tbl-cap: Fungi
df %>%
  filter(fungal_test == 1) %>%
  select(year, redcap_data_access_group, fungi___1:fungi___5) %>%
  tbl_summary(by = year, missing_text = "Missing", label = labels) %>%
  add_overall() %>%
  add_p() %>%
  separate_p_footnotes()
```

```{r}
#| label: tbl-fungi_center
#| tbl-cap: Fungi by Center
#| message: false
df %>%
  filter(fungal_test == 1) %>%
  select(year, redcap_data_access_group, fungi___1:fungi___5) %>%
  tbl_strata(
    strata = redcap_data_access_group,
    .tbl_fun =
      ~ .x %>%
        tbl_summary(by = year, missing_text = "Missing", label = labels) %>%
        add_overall() %>%
        add_p() %>%
        separate_p_footnotes()
  )
```

```{r}
#| label: tbl-fungi_cftr_mod
#| tbl-cap: Fungi by Modulator Status
#| message: false
df %>%
  filter(fungal_test == 1) %>%
  select(year, cftr_mod_spec, fungi___1:fungi___5) %>%
  tbl_strata(
    strata = year,
    .tbl_fun =
      ~ .x %>%
        tbl_summary(by = cftr_mod_spec, missing_text = "Missing", label = labels) %>%
        add_overall() %>%
        add_p() %>%
        separate_p_footnotes()
  )
```

```{r}
#| label: tbl-fungi_trikafta
#| tbl-cap: Fungi by Trikafta Status
#| message: false
df %>%
  filter(fungal_test == 1) %>%
  select(year, Trikafta, fungi___1:fungi___5) %>%
  tbl_strata(
    strata = year,
    .tbl_fun =
      ~ .x %>%
        tbl_summary(by = Trikafta, missing_text = "Missing", label = labels) %>%
        add_overall() %>%
        add_p() %>%
        separate_p_footnotes()
  )
```

# NTM

The tables below are limited to patients who had NTM testing performed.

```{r}
#| label: tbl-ntm
#| tbl-cap: NTM
df %>%
  filter(ntm_test == 1) %>%
  select(year, redcap_data_access_group, ntm___1:ntm___3) %>%
  tbl_summary(by = year, missing_text = "Missing", label = labels) %>%
  add_overall() %>%
  add_p() %>%
  separate_p_footnotes()
```

```{r}
#| label: tbl-ntm_center
#| tbl-cap: NTM by Center
#| message: false
df %>%
  filter(ntm_test == 1) %>%
  select(year, redcap_data_access_group, ntm___1:ntm___3) %>%
  tbl_strata(
    strata = redcap_data_access_group,
    .tbl_fun =
      ~ .x %>%
        tbl_summary(by = year, missing_text = "Missing", label = labels) %>%
        add_overall() %>%
        add_p() %>%
        separate_p_footnotes()
  )
```

```{r}
#| label: tbl-ntm_cftr_mod
#| tbl-cap: NTM by Modulator Status
#| message: false
df %>%
  filter(ntm_test == 1) %>%
  select(year, cftr_mod_spec, ntm___1:ntm___3) %>%
  tbl_strata(
    strata = year,
    .tbl_fun =
      ~ .x %>%
        tbl_summary(by = cftr_mod_spec, missing_text = "Missing", label = labels) %>%
        add_overall() %>%
        add_p() %>%
        separate_p_footnotes()
  )
```

```{r}
#| label: tbl-ntm_trikafta
#| tbl-cap: NTM by Trikafta Status
#| message: false
df %>%
  filter(ntm_test == 1) %>%
  select(year, Trikafta, ntm___1:ntm___3) %>%
  tbl_strata(
    strata = year,
    .tbl_fun =
      ~ .x %>%
        tbl_summary(by = Trikafta, missing_text = "Missing", label = labels) %>%
        add_overall() %>%
        add_p() %>%
        separate_p_footnotes()
  )
```

# Bacteria

```{r}
#| label: tbl-bacteria
#| tbl-cap: Bacteria
df %>%
  select(
    year, redcap_data_access_group, admit_cx_results___1:admit_cx_results___9
  ) %>%
  tbl_summary(by = year, missing_text = "Missing", label = labels) %>%
  add_overall() %>%
  add_p() %>%
  separate_p_footnotes()
```

```{r}
#| label: tbl-bacteria_center
#| tbl-cap: Bacteria by Center
#| message: false
df %>%
  select(
    year, redcap_data_access_group, admit_cx_results___1:admit_cx_results___9
  ) %>%
  tbl_strata(
    strata = redcap_data_access_group,
    .tbl_fun =
      ~ .x %>%
        tbl_summary(by = year, missing_text = "Missing", label = labels) %>%
        add_overall() %>%
        add_p() %>%
        separate_p_footnotes()
  )
```

```{r}
#| label: tbl-bacteria_cftr_mod
#| tbl-cap: Bacteria by Modulator Status
#| message: false
df %>%
  select(year, cftr_mod_spec, admit_cx_results___1:admit_cx_results___9) %>%
  tbl_strata(
    strata = year,
    .tbl_fun =
      ~ .x %>%
        tbl_summary(by = cftr_mod_spec, missing_text = "Missing", label = labels) %>%
        add_overall() %>%
        add_p() %>%
        separate_p_footnotes()
  )
```

```{r}
#| label: tbl-bacteria_trikafta
#| tbl-cap: Bacteria by Trikafta Status
#| message: false
df %>%
  select(year, Trikafta, admit_cx_results___1:admit_cx_results___9) %>%
  tbl_strata(
    strata = year,
    .tbl_fun =
      ~ .x %>%
        tbl_summary(by = Trikafta, missing_text = "Missing", label = labels) %>%
        add_overall() %>%
        add_p() %>%
        separate_p_footnotes()
  )
```
