---
title: "Serum Biomarkers of Nutrition Pre and Post CFTR Modulator Use in Children with Cystic Fibrosis"
author: "Tim Vigers"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(arsenal)
library(tidyverse)
library(readxl)
library(performance)
library(mcp)
library(lmerTest)
library(broom.mixed)
library(plotly)
library(knitr)
library(DiagrammeR)
library(lubridate)
knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "S:/PEDS/RI Biostatistics Core/Shared/Shared Projects/Vigers/CF"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Vigers/CF"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Vigers/CF"
}
knitr::opts_knit$set(root.dir = home_dir)
rm(home_dir)
source("~/GitHub/CF/get_genotype_class_severity.R")
```

# Data cleaning

```{r}
# Vitamins
vit = read_excel("./Edith Zemanick/CF Nutrition/Data_Raw/Report Vitamins_throughDecember2021.xlsx")
vit = vit %>% select(`Patient ID`,Date,VitaminA_Retinol:`Vitamin E Gamma`)
# New age at start
mods = read_excel("./Edith Zemanick/CF Nutrition/Data_Raw/Report CFTR Modulators_throughDecember2021.xlsx")
mods = mods[mods$Modulator %in% c('Kalydeco','Trikafta'),]
mods = mods %>% select(`Patient ID`,Modulator,`Earliest Date in Registry`) %>% 
  pivot_wider(id_cols = `Patient ID`,names_from = Modulator,
              values_from = `Earliest Date in Registry`)
colnames(mods)[2:ncol(mods)] = paste0(colnames(mods)[2:ncol(mods)]," Date")
mods$`First Mod Date` = pmin(mods$`Trikafta Date`,mods$`Kalydeco Date`,na.rm = T)
mods$`Second Mod Date` = pmax(mods$`Trikafta Date`,mods$`Kalydeco Date`)
# Add pancreatic status
pancreatic = read_excel("./CF Info/Sweat Tests from Internal Database_genotype class_withPancStatus.xlsx")
pancreatic = pancreatic %>% rename(`Patient ID` = PatientID) %>% select(`Patient ID`,PancreaticStatus)
# FEV1 and BMI
fev = read_excel("./Edith Zemanick/CF Nutrition/Data_Raw/Report_PFTs_ThroughDecember2021.xlsx")
fev = fev %>% select(PatientID,Date,BMI,`FEV1 % pred`) %>% rename(`Patient ID` = PatientID)
# Merge
df = full_join(vit,fev,by = c("Patient ID", "Date")) %>% filter(`Patient ID` %in% mods$`Patient ID`)
df = left_join(df,mods,by = "Patient ID")
df = left_join(df,pancreatic,by = "Patient ID")
```

```{r}
# Counts from Elin
# patients with CF in our clinical database from 2008- December 2021: 740 total, 474 in our dataset
ncdb = 740
# of patients treated with ivacaftor from 2008-2021: 58 total, 47 in dataset
# of patients treated with trikafta (ETI) from 2008-2021: 228 total, 150 in dataset 
# of patients treated with ivacaftor followed by ETI – these patients may be counted in both groups: 22 total, 17 in dataset
# Tim counts
df$Group = apply(df,1,function(r){
  if(!is.na(r["Kalydeco Date"]) & is.na(r["Trikafta Date"])){
    g = "Kalydeco"
  } else if (is.na(r["Kalydeco Date"]) & !is.na(r["Trikafta Date"])){
    g = "Trikafta"
  } else if (!is.na(r["Kalydeco Date"]) & !is.na(r["Trikafta Date"])){
    g = "Both"
  }
  return(g)
})
groups = df %>% group_by(`Patient ID`) %>% filter(row_number()==1)
# Two nutrition measures before first mod start
two_measures = df %>% 
  mutate(before_first = Date < `First Mod Date` & !is.na(VitaminA_Retinol)) %>% 
  group_by(`Patient ID`,Group) %>% count(before_first) %>% 
  filter(before_first == T,n >= 2)
# At least one nutritional measure and one weight/height measure >= 3 months after first
after_measure = df %>% 
  mutate(after_first = (Date >= `First Mod Date` %m+% months(3)) & 
           !is.na(VitaminA_Retinol)) %>%
  group_by(`Patient ID`,Group) %>% count(after_first) %>%
  filter(after_first == T,n >= 1)
# Write merged df
write.csv(df,file = "./Edith Zemanick/CF Nutrition/Data_Cleaned/merged_data.csv",
          row.names = F,na="")
write.csv(mods,file = "./Edith Zemanick/CF Nutrition/Data_Cleaned/modulators.csv",
          row.names = F,na="")
```

```{r}
# Flowchart
g = grViz("
digraph graph2 {
graph [layout = dot]
# node definitions with substituted label text
node [shape = rectangle]
a [label = '@@1']
b [label = '@@2']
c [label = '@@3']
d [label = '@@4']
e [label = '@@5']
f [label = '@@6']
g [label = '@@7']
h [label = '@@8']
i [label = '@@9']
j [label = '@@10']
k [label = '@@11']
l [label = '@@12']
m [label = '@@13']

a -> b
b -> c
c -> d
c -> e
c -> f
d -> g
e -> h
f -> i
g -> j
h -> k
i -> l
j -> m
k -> m
l -> m
}

[1]: paste0('Clinical Database (n = ', ncdb, ')')
[2]: paste0('Treated With Ivacaftor or Trikafta From 2008-2021 (n = ',length(unique(mods$`Patient ID`)), ')')
[3]: paste0('In Our Dataset (n = ',length(unique(df$`Patient ID`)), ')')
[4]: paste0('Treated With Ivacaftor Alone From 2008-2021 (n = ',as.numeric(table(groups$Group)['Kalydeco']), ')')
[5]: paste0('Treated With Trikafta Alone From 2008-2021 (n = ',as.numeric(table(groups$Group)['Trikafta']), ')')
[6]: paste0('Treated With Ivacaftor followed by Trikafta From 2008-2021 (n = ',as.numeric(table(groups$Group)['Both']), ')')
[7]: paste0('At Least Two Vitamin A Measures Prior to First Modulator (n = ',as.numeric(table(two_measures$Group)['Kalydeco']), ')')
[8]: paste0('At Least Two Vitamin A Measures Prior to First Modulator (n = ',as.numeric(table(two_measures$Group)['Trikafta']), ')')
[9]: paste0('At Least Two Vitamin A Measures Prior to First Modulator (n = ',as.numeric(table(two_measures$Group)['Both']), ')')
[10]: paste0('At Least One Vitamin A >= 3 Months After First Modulator (n = ',as.numeric(table(after_measure$Group)['Kalydeco']), ')')
[11]: paste0('At Least One Vitamin A >= 3 Months After First Modulator (n = ',as.numeric(table(after_measure$Group)['Trikafta']), ')')
[12]: paste0('At Least One Vitamin A >= 3 Months After First Modulator (n = ',as.numeric(table(after_measure$Group)['Both']), ')')
[13]: paste0('Final (n = ',length(unique(after_measure$`Patient ID`)), ')')
")
g
```

<!-- # Participant Characteristics -->

<!-- For each person, we calculated the maximum amount of time from the earliest nutrition measure before modulator start to start date, and the amount of time from modulator start date to most recent nutrition measure. The ranges of these values are presented below ("Years to start" and "Years From start," respectively). -->

<!-- ```{r results='asis'} -->
<!-- df$Sex[df$Sex == ""] = NA -->
<!-- demo = df %>% group_by(Patient.ID) %>% fill(Sex,.direction = "downup") %>% -->
<!--   filter(row_number() == 1) -->
<!-- t1 = tableby(first_mod ~ Age.at.Start..years. + Sex + genoRisk + -->
<!--                vit_measures_after + vit_measures_before + -->
<!--                notest(max_years_to_start,"min","max") + -->
<!--                notest(max_years_from_start,"min","max"), -->
<!--              data = demo, -->
<!--              control = tableby.control(numeric.stats=c("Nmiss", "median", "q1q3"),)) -->
<!-- summary(t1,test = F, -->
<!--         labelTranslations = -->
<!--           list(Age.at.Start..years. = "Age at Start (years)", -->
<!--                genoRisk = "Genotype risk group", -->
<!--                vit_measures_after = "No. of vitamin measures post", -->
<!--                vit_measures_before = "No. of vitamin measures pre", -->
<!--                max_years_to_start = "Years to start",max_years_from_start = "Years From start")) -->
<!-- ``` -->

<!-- # Piecewise longitudinal models -->

<!-- ```{r} -->
<!-- # Time relative to first mod -->
<!-- df$time = as.numeric(difftime(df$Date,df$`First Mod Date`,units = "days"))/365.25 -->
<!-- # Calculate spline things -->
<!-- df$c1 = -->
<!--   (df$time-0)*(df$time>=0) -->
<!-- df$c2 = -->
<!--   (as.numeric(difftime(df$Date,df$`Second Mod Date`,units = "days"))/365.25)*(df$Date >= df$`Second Mod Date`) -->
<!-- # Limit to 3 years prior, select columns -->
<!-- df = df %>% filter(!is.na(time) & time >= -3) %>% distinct() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- piecewise_mod = function(outcome,data,diagnostics = F){ -->
<!--   data$`Patient ID` = as.factor(data$`Patient ID`) -->
<!--   data = data %>% select(`Patient ID`,Date,`First Mod Date`,`Second Mod Date`,PancreaticStatus,BMI, -->
<!--                          all_of(outcome)) %>% drop_na(all_of(outcome)) -->
<!--   # Separate data for single and double mods -->
<!--   single = data %>% filter(c2 <= 0 | is.na(c2)) -->
<!--   double = data %>% filter(!is.na(c2)) -->
<!--   # Models -->
<!--   f_single = as.formula(paste0(outcome,"~ BMI + PancreaticStatus + time + c1 + (1|`Patient ID`)")) -->
<!--   f_double = as.formula(paste0(outcome,"~ BMI + PancreaticStatus + time + c1 +c2 + (1|`Patient ID`)")) -->
<!--   if(outcome == "BMI"){ -->
<!--     f_single = update(f_single,.~.-BMI) -->
<!--     f_double = update(f_double,.~.-BMI) -->
<!--   } -->
<!--   m_single = lmer(f_single,data = single) -->
<!--   m_double = lmer(f_double,data = double) -->
<!--   # Diagnostics if required -->
<!--   if(diagnostics){ -->
<!--     check_single = check_model(m_single) -->
<!--     check_double = check_model(m_double) -->
<!--   } else { -->
<!--     check_single = NULL -->
<!--     check_double = NULL -->
<!--   } -->
<!--   # Results -->
<!--   res_single = tidy(m_single,"fixed") -->
<!--   res_double = tidy(m_double,"fixed") -->
<!--   # Plots -->
<!--   single_plot_df = m_single@frame -->
<!--   single_plot_df$pred = predict(m_single) -->
<!--   single_plot = ggplot(single_plot_df,aes_string(x = "time",y = outcome,color = "`Patient ID`")) + -->
<!--     geom_line(aes(y = pred)) + -->
<!--     theme_bw() + theme(legend.position = "none") + xlab("Time (years)") -->
<!--   double_plot_df = m_double@frame -->
<!--   double_plot_df$pred = predict(m_double) -->
<!--   double_plot = ggplot(double_plot_df,aes_string(x = "time",y = outcome,color = "`Patient ID`")) + -->
<!--     geom_line(aes(y = pred)) + -->
<!--     theme_bw() + theme(legend.position = "none") + xlab("Time (years)") -->
<!--   # Return -->
<!--   return(list("results_single" = res_single,"results_double" = res_double, -->
<!--               "diagnostics_single" = check_single,"diagnostics_double" = check_double, -->
<!--               "plot_single" = single_plot,"plot_double" = double_plot)) -->
<!-- } -->
<!-- ``` -->

<!-- In the following models, the "time" estimate represents the slope prior to first modulator start, "c1" is the change in slope after first modulator start, and "c2" is the change in slope from first modulator to second. All models were adjusted for BMI and pancreatic status (except the BMI model, which was only adjusted for pancreatic status). -->

<!-- ## Vitamin A -->

<!-- ```{r} -->
<!-- vita = piecewise_mod(outcome = "VitaminA_Retinol",data = df,diagnostics = T) -->
<!-- ``` -->

<!-- ### Single modulator -->

<!-- ```{r results='asis'} -->
<!-- vita$plot_single -->
<!-- kable(vita$results_single,digits = 3) -->
<!-- ``` -->

<!-- ### Double modulator -->

<!-- ```{r results='asis'} -->
<!-- vita$plot_double -->
<!-- kable(vita$results_double,digits = 3) -->
<!-- ``` -->

<!-- ## BMI -->

<!-- ```{r} -->
<!-- bmi = piecewise_mod(outcome = "BMI",data = df,diagnostics = T) -->
<!-- ``` -->

<!-- ### Single modulator -->

<!-- ```{r results='asis'} -->
<!-- bmi$plot_single -->
<!-- kable(bmi$results_single,digits = 3) -->
<!-- ``` -->

<!-- ### Double modulator -->

<!-- ```{r results='asis'} -->
<!-- bmi$plot_double -->
<!-- kable(bmi$results_double,digits = 3) -->
<!-- ``` -->

<!-- # Bayesian? -->

<!-- ## BMI -->

<!-- ```{r cache=TRUE,echo=TRUE} -->
<!-- mod_df = df %>% filter(!is.na(age_second)) %>% select(Patient.ID,time,BMI) %>% drop_na() -->
<!-- model = list( -->
<!--   BMI ~ 1, # Plateau -->
<!--   1 + (1|Patient.ID) ~ 0 + time, # Joined slope -->
<!--   1 + (1|Patient.ID) ~ 0 + time, # Joined slope -->
<!--   1 + (1|Patient.ID) ~ 0 + time # Joined slope -->
<!-- ) -->
<!-- fit = mcp(model, data = mod_df,sample = "both") -->
<!-- ``` -->

<!-- ### Posterior means -->

<!-- ```{r} -->
<!-- summary(fit) -->
<!-- ``` -->

<!-- ### Posterior fit -->

<!-- ```{r} -->
<!-- plot(fit,q_fit = TRUE) + theme_bw() -->
<!-- ``` -->

<!-- ### Parameter plot -->

<!-- ```{r} -->
<!-- plot_pars(fit) -->
<!-- ``` -->

<!-- ### Hypothesis tests -->

<!-- ```{r} -->
<!-- hypothesis(fit,c("cp_1 = 0","cp_2 = 0","cp_3 = 0")) -->
<!-- ``` -->

<!-- t -->