---
title: "Pre-/Post-Trikafta (Prospective)"
author: "Tim Vigers"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(arsenal)
library(tidyverse)
library(performance)
library(AGD)
library(pracma)
library(knitr)
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "S:/PEDS/RI Biostatistics Core/Shared/Shared Projects/Vigers/CF"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Vigers/CF"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Vigers/CF"
}
knitr::opts_knit$set(root.dir = home_dir)
rm(home_dir)
```

```{r}
# Import
df = read.csv("./Christine Chan/Pre-post Trikafta Prospective/Data_Cleaned/trikafta_2022-02-8.csv",
              na.strings = c(""))
# Clean up
df$Sex = factor(df$Sex..Male.1.)
levels(df$Sex) = c("F","M")
df = df %>% group_by(Study.ID) %>% 
  mutate(trikafta_duration = sum(Time.on.trikafta.in.months)) %>% ungroup()
df[,c("Kalydeco","Orkambi","Symdeko")] = 
  lapply(df[,c("Kalydeco.1","orkambi.1","tezacaftor.ivacaftor..symdeko..1")],function(c){
    c = as.factor(c)
    levels(c) = c("No","Yes")
    return(c)
  })
# Genotype
df$Genotype = apply(df,1,function(r){
  if(tolower(r["CFTR.Mutation.1"]) == "f508del" & tolower(r["CFTR.Mutation.2"]) == "f508del"){
    g = "Homozygous F508del"
  } else if (tolower(r["CFTR.Mutation.1"]) == "f508del"){
    g = "Heterozygous F508del"
  } else {
    g = "Other"
  }
  return(g)
})
# BMI z score (count everyone over 20 as 20)
df$Age = ifelse(df$Age.at.visit. >= 20, 20, df$Age.at.visit.)
df$BMIz = y2z(df$BMI,x = df$Age,sex = df$Sex,ref=nl4.bmi)
```

# Table 1: Demographics at Baseline

For calculating BMI z scores for adults > 20, we used CDC references for 20 year olds.

```{r results='asis'}
t1 = tableby(~Age.at.visit.+Sex..Male.1.+BMIz+FEV1..+FVC....+trikafta_duration+
               Genotype+Pancreatic.Status+Kalydeco+Orkambi+Symdeko,
             data = df[df$Event.Name == "Visit 1",])
newlabels = list(Age.at.visit. = "Age (years)",Sex..Male.1. = "Sex",
                 BMIz = "BMI z score",FEV1.. = "ppFEV1",FVC.... = "ppFVC",
                 trikafta_duration = "Duration on Trikafta (months) at Visit 2",
                 Pancreatic.Status = "Pancreatic Status")
summary(t1,digits = 2,labelTranslations = newlabels)
```

# Table 2: Pre-/Post-Trikafta Comparisons

All metrics calculated based on 2 hour OGTT (0, 10, 30, 60, 90, and 120 minutes).

```{r results='asis'}
# Make dataset for HOMA2 calculations - glucose in mmol/L and cpep in nmol/L
homa = df %>% select(Study.ID,Event.Name,Glucose.0.minute,c.peptide.0.minute)
homa$Glucose.0.minute = homa$Glucose.0.minute/18
homa$c.peptide.0.minute = homa$c.peptide.0.minute/1000*0.33
write.csv(homa,"./Christine Chan/Pre-post Trikafta Prospective/Data_Cleaned/homa_data.csv",
          na = "",row.names = F)
# Import HOMA2 data (calculated with https://www.dtu.ox.ac.uk/homacalculator/download.php)
homa = read.csv("./Christine Chan/Pre-post Trikafta Prospective/Data_Cleaned/homa_calculated.csv")
df = left_join(df,homa,by = c("Study.ID", "Event.Name"))
# Glucose tolerance group
glu_cols = c("Glucose.0.minute","Glucose.60.min","Glucose.120.min")
df$Group = apply(df[,glu_cols],1,function(r){
  if(r[1]<126 & r[2] < 200 & r[3] < 140){
    return("NGT")
  } else if (r[1] >= 126 | r[3] >= 200){
    return("CFRD")
  } else {
    return("AGT")
  }
})
# convert Insulin to mcU/mL
ins_cols = colnames(df)[head(grep("insulin",tolower(colnames(df))),-2)]
df[,ins_cols] = lapply(df[,ins_cols], function(c){
  return(as.numeric(c) * 0.02869)
})
# cpeptide to pmol/L
cpep_cols = colnames(df)[head(grep("c.peptide",tolower(colnames(df))),-2)]
df[,cpep_cols] = lapply(df[,cpep_cols], function(c){
  return(c * 0.33)
})
# Calculate AUCs
df$`Glucose AUC` = apply(df %>% select(Glucose.0.minute:Glucose.120.min),1,function(r){
  trapz(c(0,10,30,60,90,120),as.numeric(r))
})
df$`C Peptide AUC` = apply(df %>% select(c.peptide.0.minute:c.peptide.120.min),1,function(r){
  trapz(c(0,10,30,60,90,120),as.numeric(r))
})
# Incremental AUCs
df$`Glucose iAUC` = apply(df %>% select(Glucose.0.minute:Glucose.120.min),1,function(r){
  r = r - r[1]
  trapz(c(0,10,30,60,90,120),as.numeric(r))
})
df$`C Peptide iAUC` = apply(df %>% select(c.peptide.0.minute:c.peptide.120.min),1,function(r){
  r = r - r[1]
  trapz(c(0,10,30,60,90,120),as.numeric(r))
})
# Other indices
# Cpeptide index = delta cpeptide 0-30/delta glucose 0-30
df$`C Peptide Index` = (df$c.peptide.30.min - df$c.peptide.0.minute)/
  (df$Glucose.30.min - df$Glucose.0.minute)
# Matsuda c peptide (500,000/√[fasting glucose*fasting cpep*mean glucose*mean cpep])   [Glucose mg/dL, cpeptide pmol/L]
glu_cols = colnames(df)[head(grep("glucose\\.\\d{1,}",tolower(colnames(df))),-2)]
df$mean_glucose = rowMeans(df[,glu_cols])
df$mean_cpep = rowMeans(df[,cpep_cols])
df$`Adapted Matsuda` = 500000/(sqrt(df$Glucose.0.minute*df$c.peptide.0.minute*
                                      df$mean_glucose*df$mean_cpep))
# C Pep ODI
df$`C Peptide ODI` = df$`C Peptide Index`/df$`Adapted Matsuda`
# iAUC ratio
df$iAUC_ratio = df$`C Peptide iAUC`/df$`Glucose iAUC`
# Add labels
newlabels["A1C.result"] = "HbA1c (%)"
newlabels["Glucose.0.minute"] = "Fasting glucose (mg/dL)"
newlabels["Glucose.60.min"] = "1hr glucose (mg/dL)"
newlabels["Glucose.120.min"] = "2hr glucose (mg/dL)"
newlabels["c.peptide.0.minute"] = "Fasting C-peptide (pmol/L)"
newlabels["iAUC_ratio"] = "C pep iAUC:Glucose iAUC"
newlabels["homa2B"] = "HOMA2 %B"
newlabels["homa2S"] = "HOMA2 %S"
newlabels["homa2IR"] = "HOMA2 IR"
p <- paired(Event.Name ~ A1C.result+BMIz+FEV1..+FVC....+Group+Glucose.0.minute+
              Glucose.60.min+Glucose.120.min+c.peptide.0.minute+
              `Glucose AUC`+`C Peptide AUC`+`C Peptide Index`+`Adapted Matsuda`+
              `C Peptide ODI`+iAUC_ratio+homa2B+homa2S+homa2IR, 
            data = df, id = Study.ID)
summary(p,pfootnote = T,labelTranslations = newlabels)
```

# Figures

## HbA1c

```{r}
ggplot(df,aes(x = Event.Name, y = A1C.result,fill = Event.Name)) + 
  geom_boxplot() + geom_jitter(width = 0.25) + 
  xlab("Visit") + ylab("HbA1c (%)") + theme_bw() + theme(legend.position = "none")
```

## Glucose

```{r}
plot_df = df %>% pivot_longer(all_of(glu_cols)) %>% select(Study.ID,Event.Name,name,value)
plot_df$name = as.numeric(gsub("Glucose|\\.|min|minute","",plot_df$name))
plot_df = plot_df %>% group_by(name,Event.Name) %>% 
  summarise(m = mean(value,na.rm = T),
            se = sd(value)/sqrt(n()),.groups = "drop")
ggplot(plot_df,aes(x = name,y = m,color = Event.Name)) + 
  geom_line() + geom_point() + 
  geom_errorbar(aes(ymin=m-(1.96*se), ymax=m+(1.96*se)), width=2) +
  xlab("Time (minutes)") + ylab("Glucose (mg/dL)") + ylim(0,200) + 
  theme_bw()
```

## Glucose

```{r}
plot_df = df %>% pivot_longer(all_of(cpep_cols)) %>% select(Study.ID,Event.Name,name,value)
plot_df$name = as.numeric(gsub("c.peptide|\\.|min|minute","",plot_df$name))
plot_df = plot_df %>% group_by(name,Event.Name) %>% 
  summarise(m = mean(value,na.rm = T),
            se = sd(value)/sqrt(n()),.groups = "drop")
ggplot(plot_df,aes(x = name,y = m,color = Event.Name)) + 
  geom_line() + geom_point() + 
  geom_errorbar(aes(ymin=m-(1.96*se), ymax=m+(1.96*se)), width=2) +
  xlab("Time (minutes)") + ylab("C Peptide (pmol/L)") + 
  theme_bw()
```

## Insulin

```{r}
plot_df = df %>% pivot_longer(all_of(ins_cols)) %>% select(Study.ID,Event.Name,name,value)
plot_df$name = as.numeric(gsub("Insulin|insulin|\\.|min|minute","",plot_df$name))
plot_df = plot_df %>% group_by(name,Event.Name) %>% 
  summarise(m = mean(value,na.rm = T),
            se = sd(value)/sqrt(n()),.groups = "drop")
ggplot(plot_df,aes(x = name,y = m,color = Event.Name)) + 
  geom_line() + geom_point() + 
  geom_errorbar(aes(ymin=m-(1.96*se), ymax=m+(1.96*se)), width=2) +
  xlab("Time (minutes)") + ylab("Insulin (mcU/mL)") + 
  theme_bw()
```
