---
title: "Body Image and Trikafta"
author: "Tim Vigers"
date: today
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
execute:
  echo: false
editor: source
---

# Data Cleaning Steps

1.  Participants who answered "I don't know" or "no" on the variable `TakingTrikafta` were excluded from these analyses.

```{r warning=FALSE}
#| include: false
library(tidyverse)
library(gtsummary)
library(kableExtra)
library(foreign)
# Read in data
df = read.spss("/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Vigers/CF/Emily Muther/Body Image and Trikafta/Data_Raw/TrikaftaBodyImage3.6.23.sav",to.data.frame = T)
# Filter
df = df %>% 
  filter(TakingTrikafta=="yes")
# Trim white space
df = df %>%
  mutate(across(where(is.character),trimws))
# Replace blanks with NA
df[df==""]=NA
```

# Descriptive analyses

## Demographics

```{r}
#| label: demographics
df %>% select(Age,Gender,Race,Ethnicity) %>%
  tbl_summary(
    by = Gender,
    statistic = list(
      all_continuous() ~ "{mean} ({sd})"
    ),
    missing_text = "(Missing)"
  )
```

## Frequency of reported changes

```{r}
#| label: changes
df %>% select(ChangestoBreathing:MoodChangesSideEf,FeelTrikafta) %>%
  tbl_summary(
    type = list(
      all_categorical() ~ "categorical"
    ),
    missing_text = "(Missing)"
  )
```

# Figure

```{r}
# | label: fig-planets
# | fig-cap: Planets

```
