---
title: "Mental Health Screening in CF"
author: "Tim Vigers"
date: "`r format(Sys.time(), '%d %B %Y')`"
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
editor: source
---

```{r}
#| include: false
library(lubridate)
library(tidyverse)
```

```{r}
# Data import
cf_gad <- read.csv("/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Vigers/CF/Emily Muther/Mental Health Screening/Data_Raw/GAD-7_General_Anxiety_Disorder_Full_Data_data_11-15-22.csv", na.strings = "")
cf_phq <- read.csv("/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Vigers/CF/Emily Muther/Mental Health Screening/Data_Raw/PHQ-9_Full_Data_data_11-11-22.csv", na.strings = "")
cf_psc <- read.csv("/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Vigers/CF/Emily Muther/Mental Health Screening/Data_Raw/PSC_Full_Data_data_11-11-22.csv", na.strings = "")
# Select and merge
cf_gad <- cf_gad %>%
  select(PAT_MRN_ID, CONTACT_DATE, GAD.7.Total.Score, GAD.7.Totals) %>%
  drop_na()
cf_phq <- cf_phq %>%
  select(PAT_MRN_ID, CONTACT_DATE, PHQ.9.Total.Score..calculated., PHQ.9.Totals) %>%
  drop_na()
cf_psc <- cf_psc %>%
  select(PAT_MRN_ID, CONTACT_DATE, Score, PSC.Totals) %>%
  drop_na()
df <- cf_gad %>%
  full_join(cf_phq, by = c("PAT_MRN_ID", "CONTACT_DATE")) %>%
  full_join(cf_psc, by = c("PAT_MRN_ID", "CONTACT_DATE"))
# Get age
pa <- read.csv("/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Vigers/CF/Emily Muther/Mental Health Screening/Data_Raw/CF_Psychosocial_Assessment_Full_Data_data_11-15-22.csv", na.strings = "")
pa <- pa %>% select(PAT_MRN_ID, CONTACT_DATE, AGE_AT_CONTACT_IN_YEARS)
# Rename columns, get distinct rows
df <- left_join(df, pa, by = c("PAT_MRN_ID", "CONTACT_DATE")) %>%
  select(PAT_MRN_ID, CONTACT_DATE, AGE_AT_CONTACT_IN_YEARS, everything()) %>%
  rename(
    id = PAT_MRN_ID, date = CONTACT_DATE, age = AGE_AT_CONTACT_IN_YEARS,
    `GAD-7 Total` = GAD.7.Total.Score,
    `GAD-7 Category` = GAD.7.Totals,
    `PHQ-9 Total` = PHQ.9.Total.Score..calculated.,
    `PHQ-9 Category` = PHQ.9.Totals,
    `PSC-17 Total` = Score,
    `PSC-17 Category` = PSC.Totals
  ) %>%
  distinct()
# Format columns and sort
df$date <- mdy(df$date)
df <- df %>%
  mutate(across(contains("Category"), factor)) %>%
  arrange(id, date)
# Write cleaned data
write.csv(df, file = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Vigers/CF/Emily Muther/Mental Health Screening/Data_Cleaned/cf_mental_health_screening.csv")
```

```{r}
skimr::skim(df)
```
