---
title: "Racial and Ethnic Differences in ETI: Outcomes"
author: "Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    number-sections: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    fig-height: 10
    fig-width: 10
    page-layout: full
    theme:
      light: flatly
      dark: darkly
editor: source
---

```{r setup}
#| include: false
# Libraries
library(tidyverse)
library(lmerTest)
library(performance)
library(segmented)
# Paths
home_dir <- switch(Sys.info()["sysname"],
  "Darwin" = "/Users/timvigers/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Vigers/CF",
  "Windows" = "C:/Users/Tim/OneDrive - The University of Colorado Denver/Vigers/CF",
  "Linux" = "/home/timvigers/OneDrive/Vigers/CF"
)
knitr::opts_knit$set(root.dir = home_dir)
```

```{r data import}
# source("/home/timvigers/GitHub/CF/Kamyron Jordan/Racial and Ethnic Differences in ETI/create_outcomes_dataset.R")
load("./Kamyron Jordan/Racial and Ethnic Differences in ETI/Data_Cleaned/outcomes_dataset.RData")
```

# Data cleaning

1. Lung function percent predicted values < 20% or > 150% were excluded.
2. Limited to 3 years before and 2 years after ETI start.
  - Based on `Modulator_trikafta_first_date` variable provided by CFFPR.
3. Hospitalizations and home IV episodes excluded.

```{r functions}
# Plots
loess_plot <- function(data = encounter, outcome, facet = F, smooth = "bs",
                       df = 10) {
  p <- ggplot(data, aes(x = Days, y = !!sym(outcome), color = Race)) +
    geom_point(
      shape = ".", aes(x = Days, y = !!sym(outcome)), inherit.aes = F,
      alpha = 0.1
    ) +
    theme_classic()
  if (smooth == "bs") {
    p <- p + geom_smooth(method = "lm", formula = y ~ splines::bs(x,
      degree = 3, df = df
    ))
  }
  if (smooth == "loess") {
    p <- p + geom_smooth(method = "loess")
  }
  if (smooth == "gam") {
    p <- p + geom_smooth(method = "gam")
  }
  if (facet) {
    p <- p + facet_wrap(~Race)
  }
  return(p)
}
```

# LOESS-smoothed outcome plots

```{r results='asis'}
#| warning: false
invisible(lapply(continuous_outcomes, function(o) {
  cat("\n")
  cat("\n")
  cat("##", o)
  cat("\n")
  cat("\n")
  print(loess_plot(outcome = o, smooth = "loess"))
  print(loess_plot(outcome = o, facet = T, smooth = "loess"))
}))
```

# B-spline smoothing (cubic, df=10)

```{r results='asis'}
#| warning: false
invisible(lapply(continuous_outcomes, function(o) {
  cat("\n")
  cat("\n")
  cat("##", o)
  cat("\n")
  cat("\n")
  print(loess_plot(outcome = o, smooth = "bs"))
  print(loess_plot(outcome = o, facet = T, smooth = "bs"))
}))
```

# B-spline smoothing (cubic, df=3)

```{r results='asis'}
#| warning: false
invisible(lapply(continuous_outcomes, function(o) {
  cat("\n")
  cat("\n")
  cat("##", o)
  cat("\n")
  cat("\n")
  print(loess_plot(outcome = o, smooth = "bs", df = 3))
  print(loess_plot(outcome = o, facet = T, smooth = "bs", df = 3))
}))
```

# GAM smoothing

```{r results='asis'}
#| warning: false
invisible(lapply(continuous_outcomes, function(o) {
  cat("\n")
  cat("\n")
  cat("##", o)
  cat("\n")
  cat("\n")
  print(loess_plot(outcome = o, smooth = "gam"))
  print(loess_plot(outcome = o, facet = T, smooth = "gam"))
}))
```

<!-- # Segmented models -->

<!-- The following models are adjusted for age group and insurance status. First, a Gaussian mixed model is fit with random intercept for patient ID. Then, the `segmented.lme` function is applied to this mixed model, with no pre-specified starting values and `npsi = 2`. The change points are treated as random effects and allowed to vary within a person. -->

<!-- ## FEV1 -->

<!-- Based on visual inspection of the LOESS plots, I expect there to be a change in slope at around 0 and maybe a second one at around 1 year. -->

<!-- ```{r} -->
<!-- load("./Kamyron Jordan/Racial and Ethnic Differences in ETI/Data_Cleaned/segmented/fev1_single_cp_fit.RData") -->
<!-- plot(fev1_single_cp_fit) -->
<!-- summary(fev1_single_cp_fit) -->
<!-- load("./Kamyron Jordan/Racial and Ethnic Differences in ETI/Data_Cleaned/segmented/fev1_double_cp_fit.RData") -->
<!-- plot(fev1_double_cp_fit) -->
<!-- summary(fev1_double_cp_fit) -->
<!-- ``` -->

<!-- ## A Bayesian approach -->

<!-- ### FEV1 -->

<!-- ```{r} -->
<!-- #| eval: false -->
<!-- load("./Kamyron Jordan/Racial and Ethnic Differences in ETI/Data_Cleaned/fev1_single_cp_fit.RData") -->
<!-- load("./Kamyron Jordan/Racial and Ethnic Differences in ETI/Data_Cleaned/fev1_double_cp_fit.RData") -->
<!-- ``` -->

<!-- - Is the second change point due to who is being collected after one year out? -->

<!-- Look at 3 years before and two after -->

<!-- 2 years for 12 and up -->
<!-- 1.5 years for 6 -->
