---
title: "CF-SuGAR Power Calculations"
author: "Tim Vigers"
date: "today"
date-format: long
format:
  html:
    fig-width: 10
    fig-height: 10
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
    theme:
      light: flatly
      dark: darkly
editor: source
---

```{r setup}
#| include: false
library(Hmisc)
library(tidyverse)
library(childsds)
library(survival)
library(gtsummary)
library(ggstats)
home_dir <- switch(Sys.info()["sysname"],
  "Darwin" = "/Users/timvigers/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Vigers/CF/Christine Chan/CF Registry",
  "Linux" = "/home/timvigers/OneDrive/Vigers/CF/Christine Chan/CF Registry"
)
github_dir <- switch(Sys.info()["sysname"],
  "Darwin" = "/Users/timvigers/Documents/GitHub",
  "Linux" = "/home/timvigers/Documents/GitHub"
)
knitr::opts_knit$set(root.dir = home_dir)
```

```{r data cleaning}
# Import data and codebook
annual <- read.csv("./Data_Raw/CFF19_Annualized_Del1.csv",
  na.strings = c("", "N/A")
)
data_dict <- readxl::read_excel("./Data_Raw/Copy of Codes for CFFPR_2018.xlsx")
data_dict$var <- paste(data_dict$field_name, data_dict$code_value, sep = "_")
# Remove those with T1D or T2D
annual <- annual %>% arrange(eDWID, ReviewYear)
annual <- annual[!annual$cfrd_status_annual %in% c(4, 5), ]
annual$cfrd_status_annual <- factor(annual$cfrd_status_annual,
  levels = 1:3,
  labels = c("CFRD-", "CFRD-", "CFRD+")
)
# Get mutations
demogs <- read.csv("./Data_Raw/CFF19_DemogCFDiag_Del1.csv")
races <- c(
  "White", "Black or African American", "American Indian or Alaska Native",
  "Asian", "Native Hawaiian or Other Pacific ", "Some other race"
)
demogs$Race <- apply(demogs, 1, function(r) {
  w <- which(r[paste0("Race", 1:6)] == 1)
  if (length(w) > 1) {
    return("More than one race")
  } else {
    return(races[w])
  }
})
demogs$Race <- factor(demogs$Race,
  levels = c(
    "White", "American Indian or Alaska Native", "Asian",
    "Black or African American", "More than one race",
    "Native Hawaiian or Other Pacific ", "Some other race"
  ),
  labels = c(
    "White", "Other race", "Other race",
    "Black or African American", "More than one race",
    "Other race", "Other race"
  )
)
demogs$Hispanicrace <- factor(demogs$Hispanicrace,
  levels = 1:2,
  labels = c("Yes", "No")
)
demogs <- demogs %>% select(eDWID, Gender, MutClass, Race, Hispanicrace)
annual <- left_join(annual, demogs, by = join_by(eDWID))
# Variable formatting
# If A_supplement_feeding is 0, then A_feeding2 is also 0 because they are not
# on any supplemental feeding
# Include all kinds of tube feeds
annual$A_feeding2[annual$A_supplement_feeding == 0] <- 0
annual$A_feeding3[annual$A_supplement_feeding == 0] <- 0
annual$A_feeding4[annual$A_supplement_feeding == 0] <- 0
tube_fields <- c("A_feeding2", "A_feeding3", "A_feeding4")
annual$tube_feeding <-
  apply(annual[, tube_fields], 1, function(r) {
    if (all(is.na(r))) {
      return(NA)
    } else {
      return(max(as.numeric(r), na.rm = T))
    }
  })
# Liver disease
liver_fields <- c("A_hepatobiliary1_3", paste0("A_hepatobiliary2_", 1:4))
annual$liver_disease <-
  apply(annual[, liver_fields], 1, function(r) {
    if (all(is.na(r))) {
      return(NA)
    } else {
      return(max(as.numeric(r), na.rm = T))
    }
  })
# Get BMI categories
annual$bmi <- annual$A_weight / ((annual$A_height / 100)^2)
annual$bmi <- coalesce(annual$A_bmivalue, annual$bmi)
annual$bmi_perc_cdc <- sds(annual$bmi,
  age = annual$Age_YrEnd,
  sex = annual$Gender, male = "M", female = "F",
  item = "bmi", ref = cdc.ref, type = "perc"
) * 100
annual$bmi_perc_who <- sds(annual$bmi,
  age = annual$Age_YrEnd,
  sex = annual$Gender, male = "M", female = "F",
  item = "bmi", ref = who.ref, type = "perc"
) * 100
annual$bmi_perc <- coalesce(annual$bmi_perc_cdc, annual$bmi_perc_who)
annual$bmi_cat <- apply(annual, 1, function(r) {
  age <- as.numeric(r["Age_YrEnd"])
  gender <- as.character(r["Gender"])
  bmi <- as.numeric(r["bmi"])
  bmi_perc <- as.numeric(r["bmi_perc"])
  if (age <= 20) {
    return(cut(bmi_perc, c(-Inf, 10, 50, 85, Inf),
      right = F,
      labels = c("Undernourished", "At Risk", "Target/Goal", "Overweight")
    ))
  } else if (age > 20) {
    if (gender == "M") {
      return(cut(bmi, c(-Inf, 18.5, 23, 25, Inf),
        right = F,
        labels = c("Undernourished", "At Risk", "Target/Goal", "Overweight")
      ))
    } else if (gender == "F") {
      return(cut(bmi, c(-Inf, 18.5, 22, 25, Inf),
        right = F,
        labels = c("Undernourished", "At Risk", "Target/Goal", "Overweight")
      ))
    }
  }
})
annual$bmi_cat <- relevel(annual$bmi_cat, ref = "Target/Goal")
# Format columns
annual$MutClass <- factor(annual$MutClass,
  levels = c("1-3", "4-5", "Oth", "N/A"),
  labels = c("1-3", "4-5", "Oth", "Unknown")
)
annual$NumPulmExacerbation <- cut(annual$NumPulmExacerbation,
  labels = c("0", "1", "2", ">=3"),
  breaks = c(0, 1, 2, 3, Inf), right = F
)
# Age groups 10 - 18 inclusive, 19 - 30 inclusive, >= 31
annual$age_group <- cut(annual$Age_YrEnd,
  breaks = c(-Inf, 10, 19, 31, Inf),
  right = F
)
# Bugs
bugs <- c(
  "A_pseudomonasaeruginosa", "A_fungalyeast1",
  "A_pulmonarycomplications1", "A_mycocultureresults3"
)
# Yes/No variables
yn_vars <- c(
  "A_corticosteroids1", "A_feeding2",
  "A_Vx770", "A_VX809comb", bugs, "tube_feeding", "liver_disease"
)
annual[, yn_vars] <- lapply(annual[, yn_vars], factor,
  levels = 0:1,
  labels = c("No", "Yes")
)
annual$A_IsOnEnzymes <- factor(annual$A_IsOnEnzymes,
  levels = c(1, 0), labels = c(" Yes", " No")
)
# FEV1 to categorical
annual$ppFEV1_cat <- cut(annual$A_FEV1_pct_predicted,
  breaks = c(0, 40, 80, 100, Inf), right = F
)
annual$ppFEV1_cat <- factor(annual$ppFEV1_cat,
  levels = c("[100,Inf)", "[80,100)", "[40,80)", "[0,40)")
)
# Males to reference group
annual$Gender <- factor(annual$Gender, levels = c("M", "F"))
# Hispanic no as reference
annual$Hispanicrace <- factor(annual$Hispanicrace, levels = c("No", "Yes"))
# Get first year of CFRD
first_cfrd <- annual %>%
  filter(cfrd_status_annual == "CFRD+") %>%
  group_by(eDWID) %>%
  summarise(first_cfrd = min(ReviewYear))
annual <- left_join(annual, first_cfrd, by = join_by(eDWID))
# Year prior to first CFRD in registry - assume negative for CFRD. Assume all
# years following are CFRD+
annual$CFRD <- NA
annual$CFRD[annual$ReviewYear < annual$first_cfrd] <- "CFRD-"
annual$CFRD[annual$ReviewYear >= annual$first_cfrd] <- "CFRD+"
annual$CFRD[is.na(annual$first_cfrd)] <- "CFRD-"
annual$CFRD <- factor(annual$CFRD, levels = c("CFRD-", "CFRD+"))
# Add formatted columns for survival analysis
annual$tstop <- ymd(paste0(annual$ReviewYear, "-12-31"))
annual$tstart <- ymd(paste0(annual$ReviewYear, "-01-01"))
annual <- annual %>%
  group_by(eDWID) %>%
  mutate(entry_date = tstart[1]) %>%
  ungroup()
# Remove those under 10
annual$age_group <- relevel(annual$age_group, ref = "[10,19)")
annual <- annual %>% filter(Age_YrEnd != 0, Age_YrEnd >= 10)
annual$age_group <- droplevels(annual$age_group)
# List of covariates
vars <- c(
  "age_group", "Gender", "bmi_perc", "bmi_cat", "MutClass", "Race",
  "Hispanicrace", "A_IsOnEnzymes", "ppFEV1_cat", "tube_feeding",
  "NumPulmExacerbation", "A_pseudomonasaeruginosa", "A_fungalyeast1",
  "A_mycocultureresults3", "A_corticosteroids1", "cfrd_status_annual",
  "A_Vx770", "A_VX809comb", "liver_disease"
)
# Nice labels for plots and tables
labels <- list(
  cfrd_status_annual = "CFRD Status", MutClass = "Mutation class",
  Race = "Race", Hispanicrace = "Hispanic",
  Gender = "Sex", A_IsOnEnzymes = "Pancreatic enzyme use",
  ppFEV1_cat = "FEV1 percent predicted category",
  A_FEV1_pct_predicted = "FEV1 percent predicted",
  A_FVC_pct_predicted = "FVC percent predicted",
  tube_feeding = "Enteric feedings", liver_disease = "Liver disease",
  A_corticosteroids1 = "Use of corticosteroids",
  NumPulmExacerbation = "Admissions for PEx", age_group = "Age group",
  height_perc = "Height percentile", bmi_cat = "BMI category",
  A_Vx770 = "Use of CFTR modulator Vx770",
  A_VX809comb = "Use of CFTR modulator Vx809 combination",
  A_pseudomonasaeruginosa = "Pseudomonas aeruginosa",
  A_fungalyeast1 = "Aspergillus (any species)",
  A_mycocultureresults3 = "Microorganisms in myco culture", eDWID = "ID",
  tstart = "Interval start", tstop = "Interval stop",
  Age_YrEnd = "Age", bmi_perc = "BMI %ile"
)
label(annual[, which(colnames(annual) %in% names(labels))]) <-
  labels[colnames(annual)[which(colnames(annual) %in% names(labels))]]
```

# Registry

## Base model

```{r}
# Origin for survival analyses
og <- ymd("2003-01-01")
# Need to use a dataframe not a tibble
annual <- as.data.frame(annual)
annual$tstart <- as.numeric(annual$tstart) - as.numeric(og)
annual$tstop <- as.numeric(annual$tstop) - as.numeric(og)
# Formula for base model
xvars <- c(
  "age_group", "Gender", "Race", "Hispanicrace", "bmi_cat", "MutClass",
  "A_IsOnEnzymes", "tube_feeding", "liver_disease", "ppFEV1_cat",
  "NumPulmExacerbation", "A_corticosteroids1"
)
y <- "Surv(time = tstart, time2 = tstop, event = as.numeric(CFRD) == 2)"
f <- as.formula(paste0(y, "~", paste0(xvars, collapse = "+")))
cox_res <- coxph(f, data = annual, cluster = eDWID)
# Forest plot and coefficients table
cox_res %>%
  tbl_regression(exponentiate = T)
ggcoef_table(cox_res,
  show_p_values = F, add_reference_rows = T, exponentiate = T,
  signif_stars = F, colour = F
)
```

## Base model plus HbA1c

```{r}
# Formula for base model
cox_res <- coxph(update(f, . ~ . + A_hgba1c), data = annual, cluster = eDWID)
# Forest plot and coefficients table
cox_res %>%
  tbl_regression(exponentiate = T)
ggcoef_table(cox_res,
  show_p_values = F, add_reference_rows = T, exponentiate = T,
  signif_stars = F, colour = F
)
```

# 1 hour OGTT glucose in CFRD

```{r}
# read in separate data files

ogtt <- read.csv("./Christine Chan/1 hour OGTT in CFRD/Data_raw/ogtt.csv")
pft <- read.csv("./Christine Chan/1 hour OGTT in CFRD/Data_raw/pfts.csv")
a1c <- read.csv("./Christine Chan/1 hour OGTT in CFRD/Data_raw/a1c.csv")
demo <- read.csv("./Christine Chan/1 hour OGTT in CFRD/Data_raw/demographics.csv")
dob <- read.csv("./Christine Chan/1 hour OGTT in CFRD/Data_raw/dob.csv")

# merge dob and pfts
pft <- merge(pft, dob, by = "MRN", all.x = T, all.y = F)
pft <- unique(pft)

# checking for dups
# t <- ogtt[,c("MRN","FName","LName")]
# t <- unique(t)
# ct <- t %>% group_by(LName,FName) %>% count(unique(MRN))

# merge ogtt and demo
demo$FName <- NULL
demo$LName <- NULL
ogtt <- ogtt %>%
  group_by(MRN, Date.of.OGTT) %>%
  filter(row_number() == 1)
ogtt_demo <- merge(ogtt, demo, by = "MRN", all.x = T, all.y = T)
ogtt_demo$Date.of.OGTT <- mdy(ogtt_demo$Date.of.OGTT)

a1c$EncounterDate <- as.Date(a1c$Date.of.A1C, format = "%m/%d/%Y")
a1c$FName <- NULL
a1c$LName <- NULL
a1c$Date.of.OGTT <- NULL
a1c$Days.Between.A1C.and.OGTT <- NULL
ogtt_demo$EncounterDate <- ogtt_demo$Date.of.OGTT
ogtt_demo_a1c <- merge(ogtt_demo, a1c, by = c("MRN", "EncounterDate"), all.x = T, all.y = T)

# find most recent FVC that is within the 90 days prior to OGTT
pft$EncounterDate <- as.Date(pft$Date.of.PFT, format = "%m/%d/%Y")
pft$FName <- NULL
pft$LName <- NULL
alldata <- merge(ogtt_demo_a1c, pft, by = c("MRN", "EncounterDate"), all.x = T, all.y = T)

# get predicted spirometry values
alldata$FVC...Pred <- NULL
alldata$FEV1...Pred <- NULL
alldata$FEF.25.75...Pred <- NULL
# dob <- pft[,c("MRN","DOB")]
# dob <- unique(dob)
# alldata <- merge(alldata,dob,by="MRN",all.x = T,all.y = F)
alldata$DOB <- as.Date(as.character(alldata$DOB), format = "%m/%d/%Y")
alldata$ht_m <- alldata$Height..cm. / 100
alldata$sexnum <- ifelse(alldata$Sex == "Male", 1, 2)
alldata$FEV1.pred <- pred_GLI(age = alldata$Age.at.PFT, height = alldata$ht_m, gender = alldata$sexnum, param = "FEV1")
alldata$FVC.pred <- pred_GLI(age = alldata$Age.at.PFT, height = alldata$ht_m, gender = alldata$sexnum, param = "FVC")
alldata$FEF.25.75.pred <- pred_GLI(age = alldata$Age.at.PFT, height = alldata$ht_m, gender = alldata$sexnum, param = "FEF2575")
alldata$FEV1.per.pred <- (alldata$FEV1.Raw / alldata$FEV1.pred) * 100
alldata$FVC.per.pred <- (alldata$FVC.Raw / alldata$FVC.pred) * 100
alldata$FEF.25.75.per.pred <- (alldata$FEF.25.75.Raw / alldata$FEF.25.75.pred) * 100
# alldata$Sex <- NULL

# hard code some corrections to data per CC
alldata[alldata$MRN == 686476, ]$X1.hour.Glucose <- ifelse(alldata[alldata$MRN == 686476, ]$Age.At.Test..years. == 14.5, 185, alldata[alldata$MRN == 686476, ]$X1.hour.Glucose)

# severity of genotype

# Red = severe or minimal function mutation
# Orange= unknown mutation status (for now)
# Yellow= partial function or mild
# Green = not CF causing, classify as "other", will most likely be seen in people with CRMS diagnosis

alldata$class2 <- ifelse(alldata$Mutation.2 %in% c(
  "1717-1G->A", "1717-1G-A", "G542X", "Q493X", "R1162X", "R553X", "R553x", "W1089X", "W1282X", "1078delT", "R75X",
  "3659delC", "621+1G->T", "621+1G>T", "394delTT", "3120 + 1g->A", "1154InsTC", "1154insTC", "1213delT",
  "1259insA", "1288insTA", "3791delC", "E60X", "K710X", "2184delA", "CFTRdele2,3", "663delT", "Glu528",
  "1461ins4", "306insA", "R709X", "CFTRdele22-24", "2711delT", "2183AA- >G", "2183delAA>G"
), "I",
ifelse(alldata$Mutation.2 %in% c("F508", "F508del", "F508del ", "G85E", "I507", "I 507", "N1303K", "A559T", "R560T", "A561E"),
  "II",
  ifelse(alldata$Mutation.2 %in% c("G551D", "G551S", "S549N"), "III",
    ifelse(alldata$Mutation.2 %in% c("R334W", "R347P", "R117H", "R117C", "P67L", "L206W", "l206w", "I206w", "D614G", "R347H", "D1152H", "3849+10kbC>T"), "IV",
      ifelse(alldata$Mutation.2 %in% c(
        "A455E", "2789+5G->A", "3849+10CT", "3849+10kbC->T", "711+3A->G", "1898+5G->T",
        "P574H", "3272-26A->G5", "3272-26A->G"
      ), "V", "")
    )
  )
)
)

alldata$severity2 <- ifelse(alldata$Mutation.2 %in% c(
  "1717-1G->A", "1717-1G-A", "G542X", "Q493X", "R1162X", "R553X", "R553x", "W1089X", "W1282X", "1078delT", "R75X",
  "3659delC", "621+1G->T", "621+1G>T", "394delTT", "3120 + 1g->A", "1154InsTC", "1154insTC", "1213delT",
  "1259insA", "1288insTA", "3791delC", "E60X", "K710X", "2184delA", "CFTRdele2,3", "663delT", "Glu528",
  "1461ins4", "306insA", "R709X", "CFTRdele22-24", "2711delT", "2183AA- >G", "2183delAA>G", "F508", "F508del", "F508del ", "G85E",
  "I507", "I 507", "N1303K", "A559T", "R560T", "A561E", "G551D", "G551S", "S549N", "1898+1G->A", "2143delT", "2183AA-G",
  "2183delAA->G", "2184insA", "S434X", "2585delT", "3120+1G->A", "3905insT", "406-1G->A", "712-1G->T", "L1245X", "Q2X", "R1158X",
  "R851X", "V520F", "L1077P", "S489X", "F311del", "W846X", "M1101K", "2622+1G->A", "S945L", "Y1092X", "R1066C", "G178R", "2957delT",
  "CFTRdele1", "W1204X", "q493x", "W57G", "1585-8G>A", "1717-8G->A", "G1244E"
), "Severe",
ifelse(alldata$Mutation.2 %in% c(
  "R334W", "R347P", "R117H", "R117C", "P67L", "L206W", "l206w", "I206w", "D614G", "R347H", "D1152H", "3849+10kbC>T", "D110H", "R1070W",
  "A455E", "2789+5G->A", "3849+10CT", "3849+10kbC->T", "711+3A->G", "1898+5G->T", "P574H", "3272-26A->G5", "3272-26A->G", "3849G->A", "H199Y", "H199y",
  "S492F", "S531P", "L1335P", "R352Q", "D1270N", "2789+2insA", "3849+10kbc->T", "Q98R", "Phe1052Val",
  "F1052V", "Tyr1014Cys", "Y1014C", "T338I", "5T", "c.2249C>T", "P750L"
), "Mild",
ifelse(alldata$Mutation.2 %in% c(
  "1262insA", "I506T", "3363delGT", "Q1209P", "3349insT", "G178R", "L467P", "317insC", "I336K",
  "ex14a", "3500-2A->G", "c.3407_3422del16", "3349insT", "1248+1G->A", "M470V", "1812-1G->A",
  "del X22-24", "Q237H", "Q237H", "W57G", "1078delA", "G178R", "2957delT", "G576A",
  "other", "Other", "Unknown", "unknown", "CFTRdele1", "1811+1.6kb A->", "UNK", "I336K", "M470V", "S1235R", "M470V", "F508C",
  "R1066H", "P205S"
), "Unk", "")
)
)

alldata$class1 <- ifelse(alldata$Mutation.1 %in% c(
  "1717-1G->A", "1717-1G-A", "G542X", "Q493X", "R1162X", "R553X", "R553x", "W1089X", "W1282X", "1078delT", "R75X",
  "3659delC", "621+1G->T", "621+1G>T", "394delTT", "3120 + 1g->A", "1154InsTC", "1154insTC", "1213delT",
  "1259insA", "1288insTA", "3791delC", "E60X", "K710X", "2184delA", "CFTRdele2,3", "663delT", "Glu528",
  "1461ins4", "306insA", "R709X", "CFTRdele22-24", "2711delT", "2183AA- >G", "2183delAA>G"
), "I",
ifelse(alldata$Mutation.1 %in% c("F508", "F508del", "F508del ", "G85E", "I507", "I 507", "N1303K", "A559T", "R560T", "A561E"), "II",
  ifelse(alldata$Mutation.1 %in% c("G551D", "G551S", "S549N"), "III",
    ifelse(alldata$Mutation.1 %in% c("R334W", "R347P", "R117H", "R117C", "P67L", "L206W", "l206w", "I206w", "D614G", "R347H", "D1152H", "3849+10kbC>T"), "IV",
      ifelse(alldata$Mutation.1 %in% c(
        "A455E", "2789+5G->A", "3849+10CT", "3849+10kbC->T", "711+3A->G", "1898+5G->T",
        "P574H", "3272-26A->G5", "3272-26A->G"
      ), "V", "")
    )
  )
)
)

alldata$severity1 <- ifelse(alldata$Mutation.1 %in% c(
  "1717-1G->A", "1717-1G-A", "G542X", "Q493X", "R1162X", "R553X", "R553x", "W1089X", "W1282X", "1078delT", "R75X",
  "3659delC", "621+1G->T", "621+1G>T", "394delTT", "3120 + 1g->A", "1154InsTC", "1154insTC", "1213delT",
  "1259insA", "1288insTA", "3791delC", "E60X", "K710X", "2184delA", "CFTRdele2,3", "663delT", "Glu528",
  "1461ins4", "306insA", "R709X", "CFTRdele22-24", "2711delT", "2183AA- >G", "2183delAA>G", "F508", "F508del", "F508del ", "G85E",
  "I507", "I 507", "N1303K", "A559T", "R560T", "A561E", "G551D", "G551S", "S549N", "1898+1G->A", "2143delT", "2183AA-G",
  "2183delAA->G", "2184insA", "S434X", "2585delT", "3120+1G->A", "3905insT", "406-1G->A", "712-1G->T", "L1245X", "Q2X", "R1158X",
  "R851X", "V520F", "L1077P", "S489X", "F311del", "W846X", "M1101K", "2622+1G->A", "S945L",
  "Y1092X", "R1066C", "G178R", "2957delT", "CFTRdele1", "W1204X", "q493x", "W57G", "1585-8G>A", "1717-8G->A", "G1244E"
), "Severe",
ifelse(alldata$Mutation.1 %in% c(
  "R334W", "R347P", "R117H", "R117C", "P67L", "L206W", "l206w", "I206w", "D614G", "R347H", "D1152H", "3849+10kbC>T", "D110H", "R1070W",
  "A455E", "2789+5G->A", "3849+10CT", "3849+10kbC->T", "711+3A->G", "1898+5G->T",
  "P574H", "3272-26A->G5", "3272-26A->G", "3849G->A", "H199Y", "H199y", "S492F", "S531P",
  "L1335P", "R352Q", "D1270N", "2789+2insA", "3849+10kbc->T", "Q98R", "Phe1052Val",
  "F1052V", "Tyr1014Cys", "Y1014C", "T338I", "5T", "c.2249C>T", "P750L"
), "Mild",
ifelse(alldata$Mutation.1 %in% c(
  "1262insA", "I506T", "3363delGT", "Q1209P", "3349insT", "G178R", "L467P", "317insC", "I336K",
  "ex14a", "3500-2A->G", "c.3407_3422del16", "3349insT", "1248+1G->A", "M470V", "1812-1G->A",
  "del X22-24", "Q237H", "Q237H", "W57G", "1078delA", "G178R", "2957delT", "G576A",
  "other", "Other", "Unknown", "unknown", "CFTRdele1", "1811+1.6kb A->", "UNK", "I336K", "M470V", "S1235R", "M470V", "F508C",
  "R1066H", "P205S"
), "Unk", "")
)
)

# 3 patients have severity2="Severe" per Christine
alldata$severity2 <- ifelse(alldata$MRN %in% c(546678, 664400, 2015506), "Severe", alldata$severity2)

alldata$genoRisk <- ifelse(alldata$severity1 == "Mild" | alldata$severity2 == "Mild", "Low",
  ifelse(alldata$severity1 == "Severe" & alldata$severity2 == "Severe", "High", "")
)

# write file of people with missing genotype risk
# write.csv(alldata[alldata$genoRisk=="",],"./Christine Chan/1 hour OGTT in CFRD/Data_raw/missing_genotype_risk.csv")


# merge back all baseline characteristics
d <- alldata[, c("MRN", "FName", "LName", "Sex", "Race", "Latino.a.", "Mutation.1", "Mutation.2", "class1", "class2", "severity1", "severity2", "genoRisk")]
d <- d[!is.na(d$FName), ]
d <- unique(d)
alldata$FName <- NULL
alldata$Latino.a. <- NULL
alldata$LName <- NULL
alldata$Sex <- NULL
alldata$Race <- NULL
alldata$Mutation.1 <- NULL
alldata$Mutation.2 <- NULL
alldata$class1 <- NULL
alldata$class2 <- NULL
alldata$severity1 <- NULL
alldata$severity2 <- NULL
alldata$genoRisk <- NULL
alldata <- merge(alldata, d, by = "MRN", all.x = T, all.y = T)


# checking for dups
# t <- alldata[,c("MRN","FName","LName")]
# t <- unique(t)
# ct <- t %>% group_by(LName,FName) %>% count(unique(MRN))

# find first OGTT
alldata$Date <- alldata$EncounterDate
o <- alldata[!is.na(alldata$X1.hour.Glucose), c("MRN", "Date")]
o <- o[order(o$MRN, o$Date), ]
o <- o %>%
  group_by(MRN) %>%
  filter(row_number() == 1)
colnames(o) <- c("MRN", "Date of first OGTT")
alldata <- merge(alldata, o, by = "MRN", all.x = T, all.y = T)
alldata <- alldata[!is.na(alldata$`Date of first OGTT`), ]

# checking ppts that Collin said had CFRD
col_check <- alldata[alldata$MRN %in% c(
  1006479, 1053930, 1078408, 1136992, 1289450, 1339023, 1413821, 1695512, 664400,
  686476, 707831, 712676, 739231, 739460, 787372, 800007, 848440, 860181, 875128, 897478, 905284, 908966,
  918124, 932695, 949042, 952250, 952252, 825118
), ]
col_check <- col_check[order(col_check$MRN, col_check$Date), ]
# write.csv(col_check,"./Christine Chan/1 hour OGTT in CFRD/Data_raw/check_cfrd.csv",na="",row.names = F)

# last 2 discrepant cases after fixing date issue
col_check2 <- alldata[alldata$MRN %in% c(686476, 825118), ]
col_check2 <- col_check2[order(col_check2$MRN, col_check2$Date), ]
# write.csv(col_check2,"./Christine Chan/1 hour OGTT in CFRD/Data_raw/check_cfrd2.csv",na="",row.names = F)

# remove all visits before first OGTT
# alldata$`Date of first OGTT` <- as.Date(as.character(alldata$`Date of first OGTT`),format="%m/%d/%Y")
alldata <- alldata[alldata$Date >= alldata$`Date of first OGTT`, ]
alldata <- alldata %>% arrange(MRN, EncounterDate)

# calculate BMI
alldata$BMI <- alldata$Weight..kg. / ((alldata$Height..cm. / 100)^2)

# reorder columns
colorder <- c(
  "MRN", "FName", "LName", "Sex", "Race", "Latino.a.", "Mutation.1", "Mutation.2", "class1", "class2", "severity1", "severity2", "genoRisk",
  "Date of first OGTT", "Date", "Age.At.Test..years.", "Fasting.Glucose", "X1.hour.Glucose", "X2.hour.Glucose", "A1C",
  "DOB", "Age.at.PFT", "FVC.Raw", "Height..cm.", "Weight..kg.", "FEV1.Raw", "FEF.25.75.Raw", "ht_m",
  "sexnum", "FEV1.pred", "FVC.pred", "FEF.25.75.pred", "FEV1.per.pred", "FVC.per.pred", "FEF.25.75.per.pred", "BMI"
)
alldata <- alldata[, colorder]
alldata <- alldata[order(alldata$MRN, alldata$Date), ]

# create combined race/ethnicity
alldata$race_eth <- ifelse(alldata$Latino.a. == "TRUE", "Hispanic", alldata$Race)

# get BMI percentile
alldata$age <- ifelse(is.na(alldata$Age.at.PFT), alldata$Age.At.Test..years., alldata$Age.at.PFT)
alldata$age_bmi <- ifelse(alldata$age > 20, 20, alldata$age)
alldata$bmip <- sds(alldata$BMI,
  age = alldata$age_bmi,
  sex = alldata$Sex, male = "Male", female = "Female",
  ref = cdc.ref,
  item = "bmi",
  type = "perc"
)
# for demographics data, multiply BMI percentile by 100
alldata$bmipercentile <- alldata$bmip * 100

# classify CFRD at each visit
alldata$cfrd_visit <- NA
alldata$cfrd_visit <- ifelse(is.na(alldata$X2.hour.Glucose), NA, ifelse(alldata$X2.hour.Glucose >= 200, 1, 0))

# find people with CFRD at baseline
cfrdbase <- alldata[alldata$Date == alldata$`Date of first OGTT` & alldata$cfrd_visit == 1, ]
before_cfrd <- length(unique(alldata$MRN))
alldata <- alldata[!(alldata$MRN %in% cfrdbase$MRN), ]
after_cfrd <- length(unique(alldata$MRN))

# number excluded with CFRD at baseline
nexcl_cfrd <- before_cfrd - after_cfrd

# create variable for CFRD groups (i.e., those who developed CFRD vs those who did not)
# and get date of first OGTT with CFRD
cfrdcheck <- alldata[alldata$cfrd_visit == 1, c("MRN", "Date", "cfrd_visit")]
cfrdcheck <- cfrdcheck[order(cfrdcheck$MRN, desc(cfrdcheck$cfrd_visit)), ]
cfrdcheck <- cfrdcheck[!is.na(cfrdcheck$MRN), ]
cfrdcheck <- cfrdcheck %>%
  group_by(MRN) %>%
  filter(row_number() == 1)
colnames(cfrdcheck) <- c("MRN", "Date of CFRD diagnosis", "CFRD")
alldata <- merge(alldata, cfrdcheck, by = "MRN", all.x = T, all.y = T)
alldata$CFRD <- ifelse(is.na(alldata$CFRD), 0, 1)

# get baseline age
baseage <- alldata[alldata$Date == alldata$`Date of first OGTT`, c("MRN", "age")]
colnames(baseage) <- c("MRN", "Base_age")
alldata <- merge(alldata, baseage, by = "MRN", all.x = T, all.y = T)

# get baseline 1 hour and 2 hour glucose
basegluc <- alldata[alldata$Date == alldata$`Date of first OGTT`, c("MRN", "X1.hour.Glucose", "X2.hour.Glucose")]
colnames(basegluc) <- c("MRN", "Baseline_1hr_glucose", "Baseline_2hr_glucose")
alldata <- merge(alldata, basegluc, by = "MRN", all.x = T, all.y = T)

# dichotomize baseline 1 hour glucose
alldata$Baseline_1hr_glucose_155 <- ifelse(alldata$Baseline_1hr_glucose >= 155, 1, 0)
alldata$Baseline_1hr_glucose_140 <- ifelse(alldata$Baseline_1hr_glucose >= 140, 1, 0)

# dichotomize baseline 2 hour glucose
alldata$Baseline_2hr_glucose_140 <- ifelse(alldata$Baseline_2hr_glucose >= 140, 1, 0)

# find date of last OGTT
lastogtt <- alldata[
  !is.na(alldata$Fasting.Glucose) | !is.na(alldata$X1.hour.Glucose) | !is.na(alldata$X2.hour.Glucose),
  c("MRN", "Date")
]
lastogtt <- lastogtt[order(lastogtt$MRN, desc(lastogtt$Date)), ]
lastogtt <- lastogtt %>%
  group_by(MRN) %>%
  filter(row_number() == 1)
colnames(lastogtt) <- c("MRN", "Date of last OGTT")
alldata <- merge(alldata, lastogtt, by = "MRN", all.x = T, all.y = T)

# read in date of modulator use
mod <- read.csv("./Christine Chan/1 hour OGTT in CFRD/Data_raw/modulators.csv", na.strings = c("", " ", NA))
mod$Kalydeco.Start.Date <- as.Date(mod$Kalydeco.Start.Date, format = "%m/%d/%Y")
mod$Orkambi.Start.Date <- as.Date(mod$Orkambi.Start.Date, format = "%m/%d/%Y")
mod$Symdeko.Start.Date <- as.Date(mod$Symdeko.Start.Date, format = "%m/%d/%Y")
mod$Trikafta.Start.Date <- as.Date(mod$Trikafta.Start.Date, format = "%m/%d/%Y")
mod$modstart <- as.Date(NA)
mod$he_modstart <- as.Date(NA)
mod$me_modstart <- as.Date(NA)
for (i in 1:nrow(mod)) {
  mod[i, ]$modstart <-
    as.Date(pmin(mod[i, ]$Kalydeco.Start.Date, mod[i, ]$Orkambi.Start.Date, mod[i, ]$Symdeko.Start.Date, mod[i, ]$Trikafta.Start.Date, na.rm = T))
  mod[i, ]$he_modstart <- as.Date(pmin(mod[i, ]$Kalydeco.Start.Date, mod[i, ]$Trikafta.Start.Date, na.rm = T))
  mod[i, ]$me_modstart <- as.Date(pmin(mod[i, ]$Orkambi.Start.Date, mod[i, ]$Symdeko.Start.Date, na.rm = T))
}
modkeep <- mod[, c("MRN", "modstart", "he_modstart", "me_modstart")]
alldata <- merge(alldata, modkeep, by = "MRN", all.x = TRUE, all.y = FALSE)
alldata$onmod <- ifelse(!is.na(alldata$modstart) & alldata$modstart <= alldata$Date, 1,
  ifelse(!is.na(alldata$modstart) & alldata$modstart > alldata$Date, 0, NA)
)
alldata$onmod <- ifelse(is.na(alldata$modstart) & is.na(alldata$onmod), 0, alldata$onmod)

alldata$onhemod <- ifelse(!is.na(alldata$he_modstart) & alldata$he_modstart <= alldata$Date, 1,
  ifelse(!is.na(alldata$he_modstart) & alldata$he_modstart > alldata$Date, 0, NA)
)
alldata$onhemod <- ifelse(is.na(alldata$he_modstart) & is.na(alldata$onhemod), 0, alldata$onhemod)

alldata$onmemod <- ifelse(!is.na(alldata$me_modstart) & alldata$me_modstart <= alldata$Date, 1,
  ifelse(!is.na(alldata$me_modstart) & alldata$me_modstart > alldata$Date, 0, NA)
)
alldata$onmemod <- ifelse(is.na(alldata$me_modstart) & is.na(alldata$onmemod), 0, alldata$onmemod)


alldata$FEV.1.per.pred_FVC.per.pred <- alldata$FEV1.per.pred / alldata$FVC.per.pred

# for analyses about prediction of CFRD, we need to exclude those who only have one OGTT
# can use alldata for mixed models of PFTs and BMI
oneogtt <- alldata[alldata$`Date of first OGTT` == alldata$`Date of last OGTT`, ]
multogtt <- alldata[!(alldata$MRN %in% oneogtt$MRN), ]

# have CFRD indicator
# create variable for follow-up time
# in those who do not develop CFRD, this is the time between first and last OGTT, and they are censored
# for those who develop CFRD, this is time between first OGTT and diagnosis of CFRD
multogtt$Follow_up_time_yrs <- ifelse(multogtt$CFRD == 1, (multogtt$`Date of CFRD diagnosis` - multogtt$`Date of first OGTT`) / 365.25,
  (multogtt$`Date of last OGTT` - multogtt$`Date of first OGTT`) / 365.25
)

# get age at diagnosis of CFRD
multogtt$age_at_CFRD_dx <- ifelse(multogtt$CFRD == 1, (multogtt$`Date of CFRD diagnosis` - multogtt$DOB) / 365.25, NA)

# create categorical time
multogtt$cat_time <- as.factor(round_any(multogtt$Follow_up_time_yrs, 0.5))
# need a time variable for mixed models
multogtt$time <- as.numeric((multogtt$Date - multogtt$`Date of first OGTT`) / 365.25)
multogtt$cat_time2 <- as.factor(round_any(multogtt$time, 0.5))

# get number of participants in each cohort
n_alldata <- length(unique(alldata$MRN))
n_multogtt <- length(unique(multogtt$MRN))
# number of participants in each cohort who developed CFRD
n_alldata_cfrd <- length(unique(alldata[alldata$CFRD == 1, ]$MRN))
n_multogtt_cfrd <- length(unique(multogtt[multogtt$CFRD == 1, ]$MRN))

# create dataset with baseline only
baseline_mult <- multogtt[multogtt$Date == multogtt$`Date of first OGTT`, ]
baseline_mult$onmod_baseline <- as.factor(baseline_mult$onmod)
baseline_all <- alldata[alldata$Date == alldata$`Date of first OGTT`, ]
baseline_all$onmod_baseline <- as.factor(baseline_all$onmod)
# find patients who were put on modulators during follow-up
evermod <- alldata %>%
  group_by(MRN) %>%
  summarise(max(onmod))
baseline_all <- merge(baseline_all, evermod, by = "MRN", all.x = T, all.y = T)
baseline_all$modstarted_fup <- as.factor(ifelse(baseline_all$onmod_baseline == 0 & baseline_all$`max(onmod)` == 1, 1, 0))
baseline_mult <- merge(baseline_mult, evermod, by = "MRN", all.x = T, all.y = F)
baseline_mult$modstarted_fup <- as.factor(ifelse(baseline_mult$onmod_baseline == 0 & baseline_mult$`max(onmod)` == 1, 1, 0))

################## FILL IN MISSING A1c, BMI, PFT AT BASELINE

# find most recent A1c that is within the 90 days prior to OGTT or up to 14 days after OGTT
a1c$Date.of.A1C <- as.Date(a1c$Date.of.A1C, format = "%m/%d/%Y")
baseline_mult$A1C <- unlist(apply(baseline_mult, 1, function(r) {
  Date <- r["Date of first OGTT"]
  ID <- as.numeric(r["MRN"])
  d <- a1c %>% filter(MRN == ID)
  d$days <- difftime(d$Date.of.A1C, Date, units = "days")
  d <- d %>% filter(days <= 14 & days >= -90)
  a <- d$A1C[which.min(abs(difftime(d$Date.of.A1C, Date)))]
  if (is.na(Date) | nrow(d) == 0) {
    a <- NA
  }
  return(a)
}))
baseline_all$A1C <- unlist(apply(baseline_all, 1, function(r) {
  Date <- r["Date of first OGTT"]
  ID <- as.numeric(r["MRN"])
  d <- a1c %>% filter(MRN == ID)
  d$days <- difftime(d$Date.of.A1C, Date, units = "days")
  d <- d %>% filter(days <= 14 & days >= -90)
  a <- d$A1C[which.min(abs(difftime(d$Date.of.A1C, Date)))]
  if (is.na(Date) | nrow(d) == 0) {
    a <- NA
  }
  return(a)
}))

# find most recent FEV1 that is within the 90 days prior to OGTT or up to 14 days after OGTT
pfttemp <- alldata[!is.na(alldata$FEV1.per.pred), ]
pfttemp$Date.of.PFT <- as.Date(pfttemp$Date, format = "%m/%d/%Y")
baseline_mult$FEV1.per.pred <- unlist(apply(baseline_mult, 1, function(r) {
  Date <- r["Date of first OGTT"]
  ID <- as.numeric(r["MRN"])
  d <- pfttemp %>% filter(MRN == ID)
  d$days <- difftime(d$Date.of.PFT, Date, units = "days")
  d <- d %>% filter(days <= 14 & days >= -90)
  a <- d$FEV1.per.pred[which.min(abs(difftime(d$Date.of.PFT, Date)))]
  if (is.na(Date) | nrow(d) == 0) {
    a <- NA
  }
  return(a)
}))
baseline_all$FEV1.per.pred <- unlist(apply(baseline_all, 1, function(r) {
  Date <- r["Date of first OGTT"]
  ID <- as.numeric(r["MRN"])
  d <- pfttemp %>% filter(MRN == ID)
  d$days <- difftime(d$Date.of.PFT, Date, units = "days")
  d <- d %>% filter(days <= 14 & days >= -90)
  a <- d$FEV1.per.pred[which.min(abs(difftime(d$Date.of.PFT, Date)))]
  if (is.na(Date) | nrow(d) == 0) {
    a <- NA
  }
  return(a)
}))
# didn't add any PFTs so won't repeat code for FVC

# find most recent BMI that is within the 90 days prior to OGTT or up to 14 days after OGTT
bmitemp <- alldata[!is.na(alldata$BMI), ]
bmitemp$Date.of.BMI <- as.Date(bmitemp$Date, format = "%m/%d/%Y")
baseline_mult$BMI <- unlist(apply(baseline_mult, 1, function(r) {
  Date <- r["Date of first OGTT"]
  ID <- as.numeric(r["MRN"])
  d <- bmitemp %>% filter(MRN == ID)
  d$days <- difftime(d$Date.of.BMI, Date, units = "days")
  d <- d %>% filter(days <= 14 & days >= -90)
  a <- d$BMI[which.min(abs(difftime(d$Date.of.BMI, Date)))]
  if (is.na(Date) | nrow(d) == 0) {
    a <- NA
  }
  return(a)
}))
baseline_all$BMI <- unlist(apply(baseline_all, 1, function(r) {
  Date <- r["Date of first OGTT"]
  ID <- as.numeric(r["MRN"])
  d <- bmitemp %>% filter(MRN == ID)
  d$days <- difftime(d$Date.of.BMI, Date, units = "days")
  d <- d %>% filter(days <= 14 & days >= -90)
  a <- d$BMI[which.min(abs(difftime(d$Date.of.BMI, Date)))]
  if (is.na(Date) | nrow(d) == 0) {
    a <- NA
  }
  return(a)
}))

#############################################################

# create multogtt with time <4 years since there is little data beyond that
multogtt_reduced <- multogtt[multogtt$time <= 4, ]


##############
# DESC STATS #
##############

# table of demographics in those with at least one pre-CFRD OGTT
demovars <- c(
  "Sex", "race_eth", "age", "genoRisk", "Fasting.Glucose", "X1.hour.Glucose", "X2.hour.Glucose", "onmod_baseline", "modstarted_fup",
  "A1C", "FEV1.per.pred", "FVC.per.pred", "BMI", "bmipercentile", "FEV.1.per.pred_FVC.per.pred"
)
# Taking out these clinical variables - if they are to be added to table 1, need to figure out how
# because they come from PFT visits, not the same date as OGTT
#              "BMI","FEV1.per.pred","FVC.per.pred","FEF.25.75.per.pred","bmip")
t1_alldata <- CreateTableOne(data = baseline_all, vars = demovars)
t1_alldata <- print(t1_alldata, printToggle = F, varLabels = TRUE, missing = T, showAllLevels = T, test = F)

# table of demographics in those with at least one pre-CFRD OGTT by sex
t1_alldata_sex <- CreateTableOne(data = baseline_all, vars = demovars, strata = "Sex")
t1_alldata_sex <- print(t1_alldata_sex, printToggle = F, varLabels = TRUE, missing = T, showAllLevels = T)

# table of demographics in those with more than 1 OGTT
t1_multogtt <- CreateTableOne(data = baseline_mult, vars = c(demovars, "Follow_up_time_yrs"))
t1_multogtt <- print(t1_multogtt, printToggle = F, varLabels = TRUE, missing = T, showAllLevels = T, test = F)

# table of demographics in those with more than 1 OGTT stratified by progression
t1_multogtt_prog <- CreateTableOne(data = baseline_mult, vars = c(demovars, "Follow_up_time_yrs", "age_at_CFRD_dx"), strata = "CFRD")
t1_multogtt_prog <- print(t1_multogtt_prog, printToggle = F, varLabels = TRUE, missing = T, showAllLevels = T, test = T)

# table of demographics in those with more than 1 OGTT by sex
t1_multogtt_sex <- CreateTableOne(data = baseline_mult, vars = demovars, strata = "Sex")
t1_multogtt_sex <- print(t1_multogtt_sex, printToggle = F, varLabels = TRUE, missing = T, showAllLevels = T)

# compare baseline glucose values in those who developed CFRD and those who did not
# added other vars too
gluctable <- CreateTableOne(baseline_mult, vars = demovars, strata = "CFRD")
gluctable <- print(gluctable, printToggle = F, varLabels = TRUE, missing = T, showAllLevels = T, test = T)

########################
# LOGISTIC REGRESSIONS #
########################

# logistic regression of 1 hour and 2 hour glucose predicting cfrd
log1 <- glm(data = baseline_mult, CFRD ~ Baseline_1hr_glucose, family = "binomial")
or1 <- exp(cbind(OR = coef(log1), confint(log1)))
log1_adj <- glm(data = baseline_mult, CFRD ~ Baseline_1hr_glucose + Base_age + Sex, family = "binomial")
or1_adj <- exp(cbind(OR = coef(log1_adj), confint(log1_adj)))

# add interaction with sex
log1_adj_int <- glm(data = baseline_mult, CFRD ~ Baseline_1hr_glucose + Base_age + Sex + Sex * Baseline_1hr_glucose, family = "binomial")
or1_adj_int <- exp(cbind(OR = coef(log1_adj_int), confint(log1_adj_int)))

log1_cat <- glm(data = baseline_mult, CFRD ~ Baseline_1hr_glucose_155, family = "binomial")
or1_cat <- exp(cbind(OR = coef(log1_cat), confint(log1_cat)))
log1_cat_adj <- glm(data = baseline_mult, CFRD ~ Baseline_1hr_glucose_155 + Base_age + Sex, family = "binomial")
or1_cat_adj <- exp(cbind(OR = coef(log1_cat_adj), confint(log1_cat_adj)))

log1_cat_140 <- glm(data = baseline_mult, CFRD ~ Baseline_1hr_glucose_140, family = "binomial")
or1_cat_140 <- exp(cbind(OR = coef(log1_cat_140), confint(log1_cat_140)))
log1_cat_adj_140 <- glm(data = baseline_mult, CFRD ~ Baseline_1hr_glucose_140 + Base_age + Sex, family = "binomial")
or1_cat_adj_140 <- exp(cbind(OR = coef(log1_cat_adj_140), confint(log1_cat_adj_140)))

# add interaction with sex
log1_cat_adj_int <- glm(
  data = baseline_mult, CFRD ~ Baseline_1hr_glucose_155 + Base_age + Sex + Sex * Baseline_1hr_glucose_155,
  family = "binomial"
)
or1_cat_adj_int <- exp(cbind(OR = coef(log1_cat_adj_int), confint(log1_cat_adj_int)))

log2 <- glm(data = baseline_mult, CFRD ~ Baseline_2hr_glucose, family = "binomial")
or2 <- exp(cbind(OR = coef(log2), confint(log2)))

log2_adj <- glm(data = baseline_mult, CFRD ~ Baseline_2hr_glucose + Base_age + Sex, family = "binomial")
or2_adj <- exp(cbind(OR = coef(log2_adj), confint(log2_adj)))

# add interaction with sex
log2_adj_int <- glm(data = baseline_mult, CFRD ~ Baseline_2hr_glucose + Base_age + Sex + Sex * Baseline_2hr_glucose, family = "binomial")
or2_adj_int <- exp(cbind(OR = coef(log2_adj_int), confint(log2_adj_int)))

# ROC for 1 hour glucose
# get predicted values from logistic regression
baseline_mult$pred_1hr <- predict(log1, type = "response", data.frame = baseline_mult)
# perform the ROC analysis
roc1 <- roc(data = baseline_mult, response = CFRD, predictor = X1.hour.Glucose)
# find the cutoff that maximizes the Youden Index
coords1 <- coords(roc1, "b", ret = c("t", "specificity", "sensitivity"), best.method = "youden") # default

# ROC for 2 hour glucose
baseline_mult$pred_2hr <- predict(log2, type = "response", data.frame = baseline_mult)
roc2 <- roc(data = baseline_mult, response = CFRD, predictor = X2.hour.Glucose)
coords2 <- coords(roc2, "b", ret = c("t", "specificity", "sensitivity"), best.method = "youden") # default

##############
# COX MODELS #
##############

# CPH model for baseline 1 hour glucose
cox1hr <- coxph(Surv(Follow_up_time_yrs, CFRD) ~ Baseline_1hr_glucose, data = baseline_mult)
```

# Questions for Deb

- Part of the reason that we split the data into 3 eras was because the PH assumption was violated in the full model. How do you want to handle that for the power calculations?
