---
title: "Title"
author: "Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
    theme:
      light: flatly
      dark: darkly
editor: source
---

```{r setup}
#| include: false
library(tidyverse)
library(lmerTest)
library(emmeans)
switch(Sys.info()[["sysname"]],
  Windows = {
    home_dir <- "C:/Users/Tim/OneDrive - The University of Colorado Denver/Vigers/CF"
  },
  Darwin = {
    home_dir <- "/Users/timvigers/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Vigers/CF"
  }
)
knitr::opts_knit$set(root.dir = home_dir)
```

```{r data cleaning}
# Import data cleaned for Katie's analysis
df <- read.csv("./Christine Chan/EnVision CF/Data_Clean/nacfc_2024_analysis_data.csv",
  na.strings = ""
)
glucose <- paste0("timepoint_", c(0, 10, 30, 60, 90, 120, 150, 180), "_min")
# Remove those missing all OGTT values
long_df <- df %>% select(study_id, redcap_event_name, all_of(glucose), Diagnosis)
long_df <- long_df[rowSums(is.na(long_df)) < length(glucose), ]
# Long OGTTs
long_df <- long_df %>%
  pivot_longer(timepoint_0_min:timepoint_180_min,
    names_to = "Time", values_to = "Glucose",
    names_pattern = "timepoint_(.*)_min"
  )
# Time as a factor
long_df$Time = factor(long_df$Time,levels = c(0, 10, 30, 60, 90, 120, 150, 180))
```

```{r mixed models}
mod <- lmer(Glucose ~ Time * Diagnosis + (1 | study_id), data = long_df)
means <- data.frame(emmeans(mod, ~ Time + Diagnosis, pbkrtest.limit = 1e4))
```

# Figure

```{r}
#| label: fig-mixed-model
#| fig-cap: Model means by timepoint
ggplot(means, aes(x = Time, y = emmean, color = Diagnosis, group = Diagnosis)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL),width=0.2) +
  geom_line() +
  theme_classic() +
  ylab("Mean Glucose")
```
