---
title: "HbA1c, random glucose, and CFRD"
author: "Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    fig-width: 12
    fig-height: 9
    page-layout: full
editor: source
---

```{r setup}
#| include: false
library(tidyverse)
library(rpart)
library(rpart.plot)
knitr::opts_knit$set(root.dir = "/Users/timvigers/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Vigers/CF/Christine Chan/CF Registry")
```

```{r data cleaning}
# Import data
encounters <- read.csv("./Data_Raw/CFF19_encountersMerged_Del1.csv",
  na.strings = c("", "N/A")
)
# Demographic data
demo <- read.csv("./Data_Raw/CFF19_DemogCFDiag_Del1.csv",
  na.strings = c("", "N/A")
)
# Race
races <- c(
  "White", "Black or African American", "American Indian or Alaska Native",
  "Asian", "Native Hawaiian or Other Pacific Islander", "Some other race"
)
demo$Race <- apply(demo, 1, function(r) {
  w <- which(r[paste0("Race", 1:6)] == 1)
  if (length(w) == 0) {
    "Unknown"
  } else if (length(w) > 1) {
    "More than one race"
  } else {
    races[w]
  }
})
demo$Race <- factor(demo$Race,
  levels = c(
    "White", "Black or African American", "American Indian or Alaska Native",
    "Asian", "More than one race", "Native Hawaiian or Other Pacific Islander",
    "Some other race"
  ),
  labels = c(
    "White", "Black or African American", "Other race", "Other race",
    "More than one race", "Other race", "Other race"
  )
)
demo$Hispanicrace <- factor(demo$Hispanicrace,
  levels = 1:2,
  labels = c("Yes", "No")
)
# F508
demo$F508 <- factor(demo$F508,
  levels = 1:3,
  labels = c("F508del/F508del", "F508del/Other", "Other/Other")
)
# Merge
encounters <- left_join(
  encounters,
  demo %>% select(eDWID, Race, Hispanicrace, Gender, F508, MutClass),
  by = join_by(eDWID)
)
# CFRD by OGTT two hour
encounters$cfrd_ogtt <- factor(encounters$twohour_bloodglucose >= 200,
  levels = c(F, T), labels = c("CFRD-", "CFRD+")
)
# CFRD by registry definition
encounters$cfrd_registry <- factor(encounters$cfrd_status,
  levels = c(1:5), labels = c("CFRD-", "CFRD-", "CFRD+", "CFRD-", "CFRD-")
)
# Dataset for decision trees
encounters <- encounters %>%
  select(
    eDWID, reviewyear, encounternum, rand_bloodglucose, hgba1c,
    ogttfast_bloodglucose, twohour_bloodglucose, cfrd_ogtt, cfrd_registry
  )
```

# Random forests

```{r}
tree1 <- rpart(cfrd_ogtt ~ ogttfast_bloodglucose + hgba1c, data = encounters,
               control = rpart.control(xval = 100))
rpart.plot(tree1, type = 1, extra = 8)
```
