---
title: "CF Registry Analysis - Lung Function"
author: "Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    fig-width: 12
    fig-height: 9
    page-layout: full
editor: source
---

```{r setup}
#| include: false
library(ggplot2)
library(gtsummary)
library(gt)
library(pROC)
library(ggrepel)
library(childsds)
library(labelled)
library(Hmisc)
library(lmerTest)
library(multcomp)
library(tidyverse)
home_dir <- switch(
  Sys.info()["sysname"],
  "Darwin" = "/Users/tim/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Vigers/CF/Christine Chan/CF Registry",
  "Windows" = "C:/Users/tim/OneDrive - The University of Colorado Denver/Vigers/CF/Christine Chan/CF Registry",
  "Linux" = "/home/tim/OneDrive/Vigers/CF/Christine Chan/CF Registry"
)
github_dir <- switch(
  Sys.info()["sysname"],
  "Darwin" = "/Users/timvigers/GitHub",
  "Windows" = "C:/Users/Tim/GitHub",
  "Linux" = "/home/tim/GitHub"
)
knitr::opts_knit$set(root.dir = home_dir)
set.seed(1017)
```

# Participant characteristics at CFRD diagnosis by diagnostic method

```{r}
#| warning: false
#| message: false
# Import data and codebook
setwd(home_dir)
annual <- read.csv(
  "./Data_Raw/CFF19_Annualized_Del1.csv",
  na.strings = c("", "N/A")
)
data_dict <- readxl::read_excel("./Data_Raw/Copy of Codes for CFFPR_2018.xlsx")
data_dict$var <- paste(data_dict$field_name, data_dict$code_value, sep = "_")
# Remove those with T1D or T2D
annual <- annual |> arrange(eDWID, ReviewYear)
annual <- annual[!annual$cfrd_status_annual %in% c(4, 5), ]
annual$cfrd_status_annual <- factor(
  annual$cfrd_status_annual,
  levels = 1:3,
  labels = c("CFRD-", "CFRD-", "CFRD+")
)
# Get mutations
demogs <- read.csv("./Data_Raw/CFF19_DemogCFDiag_Del1.csv")
races <- c(
  "White",
  "Black or African American",
  "American Indian or Alaska Native",
  "Asian",
  "Native Hawaiian or Other Pacific ",
  "Some other race"
)
demogs$Race <- apply(demogs, 1, function(r) {
  w <- which(r[paste0("Race", 1:6)] == 1)
  if (length(w) > 1) {
    return("More than one race")
  } else {
    return(races[w])
  }
})
demogs$Race <- factor(
  demogs$Race,
  levels = c(
    "White",
    "American Indian or Alaska Native",
    "Asian",
    "Black or African American",
    "More than one race",
    "Native Hawaiian or Other Pacific ",
    "Some other race"
  ),
  labels = c(
    "White",
    "Other race",
    "Other race",
    "Black or African American",
    "More than one race",
    "Other race",
    "Other race"
  )
)
demogs$Hispanicrace <- factor(
  demogs$Hispanicrace,
  levels = 1:2,
  labels = c("Yes", "No")
)
demogs <- demogs |> select(eDWID, Gender, MutClass, Race, Hispanicrace)
annual <- left_join(annual, demogs, by = join_by(eDWID))
# Variable formatting
# If A_supplement_feeding is 0, then A_feeding2 is also 0 because they are not
# on any supplemental feeding
# Include all kinds of tube feeds
annual$A_feeding2[annual$A_supplement_feeding == 0] <- 0
annual$A_feeding3[annual$A_supplement_feeding == 0] <- 0
annual$A_feeding4[annual$A_supplement_feeding == 0] <- 0
tube_fields <- c("A_feeding2", "A_feeding3", "A_feeding4")
annual$tube_feeding <-
  apply(annual[, tube_fields], 1, function(r) {
    if (all(is.na(r))) {
      return(NA)
    } else {
      return(max(as.numeric(r), na.rm = T))
    }
  })
# Liver disease
liver_fields <- c("A_hepatobiliary1_3", paste0("A_hepatobiliary2_", 1:4))
annual$liver_disease <-
  apply(annual[, liver_fields], 1, function(r) {
    if (all(is.na(r))) {
      return(NA)
    } else {
      return(max(as.numeric(r), na.rm = T))
    }
  })
# Get BMI categories
annual$bmi <- annual$A_weight / ((annual$A_height / 100)^2)
annual$bmi <- coalesce(annual$A_bmivalue, annual$bmi)
annual$bmi_perc_cdc <- sds(
  annual$bmi,
  age = annual$Age_YrEnd,
  sex = annual$Gender,
  male = "M",
  female = "F",
  item = "bmi",
  ref = cdc.ref,
  type = "perc"
) *
  100
annual$bmi_perc_who <- sds(
  annual$bmi,
  age = annual$Age_YrEnd,
  sex = annual$Gender,
  male = "M",
  female = "F",
  item = "bmi",
  ref = who.ref,
  type = "perc"
) *
  100
annual$bmi_perc <- coalesce(annual$bmi_perc_cdc, annual$bmi_perc_who)
annual$bmi_cat <- apply(annual, 1, function(r) {
  age <- as.numeric(r["Age_YrEnd"])
  gender <- as.character(r["Gender"])
  bmi <- as.numeric(r["bmi"])
  bmi_perc <- as.numeric(r["bmi_perc"])
  if (age <= 20) {
    return(cut(
      bmi_perc,
      c(-Inf, 10, 50, 85, Inf),
      right = F,
      labels = c("Undernourished", "At Risk", "Target/Goal", "Overweight")
    ))
  } else if (age > 20) {
    if (gender == "M") {
      return(cut(
        bmi,
        c(-Inf, 18.5, 23, 25, Inf),
        right = F,
        labels = c(
          "Undernourished",
          "At Risk",
          "Target/Goal",
          "Overweight"
        )
      ))
    } else if (gender == "F") {
      return(cut(
        bmi,
        c(-Inf, 18.5, 22, 25, Inf),
        right = F,
        labels = c(
          "Undernourished",
          "At Risk",
          "Target/Goal",
          "Overweight"
        )
      ))
    }
  }
})
annual$bmi_cat <- relevel(annual$bmi_cat, ref = "Target/Goal")
# Raw values for adults, percentiles for peds
annual$bmi_adult = annual$bmi
annual$bmi_adult[annual$Age_YrEnd <= 20] = NA
annual$bmi_perc = annual$bmi_perc
annual$bmi_perc[annual$Age_YrEnd > 20] = NA
# Labels
var_label(annual$bmi) = "BMI (all participants)"
var_label(annual$bmi_perc) = "BMI percentile (age <= 20)"
var_label(annual$bmi_adult) = "BMI value (age > 20)"
var_label(annual$bmi_cat) = "BMI category"
# Format columns
annual$MutClass <- factor(
  annual$MutClass,
  levels = c("1-3", "4-5", "Oth", "N/A"),
  labels = c("1-3", "4-5", "Oth", "Unknown")
)
annual$NumPulmExacerbation <- cut(
  annual$NumPulmExacerbation,
  labels = c("0", "1", "2", ">=3"),
  breaks = c(0, 1, 2, 3, Inf),
  right = F
)
# Age groups 10 - 18 inclusive, 19 - 30 inclusive, >= 31
annual$age_group <- cut(
  annual$Age_YrEnd,
  breaks = c(-Inf, 10, 19, 31, Inf),
  right = F
)
# Bugs
bugs <- c(
  "A_pseudomonasaeruginosa",
  "A_fungalyeast1",
  "A_pulmonarycomplications1",
  "A_mycocultureresults3",
  "A_cultureresults3"
)
# Yes/No variables
annual$cfrd_treatment_options1[annual$cfrd_treatment_options1 == 2] <- NA
annual$cfrd_treatment_options4[annual$cfrd_treatment_options1 == 4] <- NA
yn_vars <- c(
  "A_corticosteroids1",
  "A_feeding2",
  "A_Vx770",
  "A_VX809comb",
  bugs,
  "tube_feeding",
  "liver_disease",
  "cfrd_treatment",
  "cfrd_treatment_options1",
  "cfrd_treatment_options2",
  "cfrd_treatment_options3",
  "cfrd_treatment_options4"
)
annual[, yn_vars] <- lapply(
  annual[, yn_vars],
  factor,
  levels = 0:1,
  labels = c("No", "Yes")
)
annual$A_IsOnEnzymes <- factor(
  annual$A_IsOnEnzymes,
  levels = c(1, 0),
  labels = c("Yes", " No")
)
# FEV1 to categorical
annual$ppFEV1_cat <- cut(
  annual$A_FEV1_pct_predicted,
  breaks = c(0, 40, 80, 100, Inf),
  right = F
)
annual$ppFEV1_cat <- factor(
  annual$ppFEV1_cat,
  levels = c("[100,Inf)", "[80,100)", "[40,80)", "[0,40)")
)
# Males to reference group
annual$Gender <- factor(annual$Gender, levels = c("M", "F"))
# Hispanic no as reference
annual$Hispanicrace <- factor(annual$Hispanicrace, levels = c("No", "Yes"))
# Get first year of CFRD
first_cfrd <- annual |>
  filter(cfrd_status_annual == "CFRD+") |>
  group_by(eDWID) |>
  summarise(first_cfrd = min(ReviewYear), age_dx = min(Age_YrEnd))
annual <- left_join(annual, first_cfrd, by = join_by(eDWID))
# Year prior to first CFRD in registry - assume negative for CFRD. Assume all
# years following are CFRD+
annual$CFRD <- NA
annual$CFRD[annual$ReviewYear < annual$first_cfrd] <- "CFRD-"
annual$CFRD[annual$ReviewYear >= annual$first_cfrd] <- "CFRD+"
annual$CFRD[is.na(annual$first_cfrd)] <- "CFRD-"
annual$CFRD <- factor(annual$CFRD, levels = c("CFRD-", "CFRD+"))
# Add formatted columns for survival analysis
annual$tstop <- ymd(paste0(annual$ReviewYear, "-12-31"))
annual$tstart <- ymd(paste0(annual$ReviewYear, "-01-01"))
annual <- annual |>
  group_by(eDWID) |>
  mutate(entry_date = tstart[1]) |>
  ungroup()
# Remove those under 10
annual$age_group <- relevel(annual$age_group, ref = "[10,19)")
annual <- annual |> filter(Age_YrEnd != 0, Age_YrEnd >= 10)
annual$age_group <- droplevels(annual$age_group)
# Get first CFRD again for people who were diagnosed before age 10
first_cfrd <- annual |>
  filter(cfrd_status_annual == "CFRD+") |>
  group_by(eDWID) |>
  summarise(first_cfrd = min(ReviewYear), age_dx = min(Age_YrEnd))
annual$first_cfrd = NULL
annual <- left_join(annual, first_cfrd, by = join_by(eDWID))
# Number of visits
annual <- annual |> group_by(eDWID) |> mutate(years_with_data = n())
# List of covariates
vars <- c(
  "age_group",
  "Gender",
  "bmi_perc",
  "bmi_cat",
  "MutClass",
  "Race",
  "Hispanicrace",
  "A_IsOnEnzymes",
  "ppFEV1_cat",
  "tube_feeding",
  "NumPulmExacerbation",
  "A_pseudomonasaeruginosa",
  "A_fungalyeast1",
  "A_mycocultureresults3",
  "A_corticosteroids1",
  "cfrd_status_annual",
  "A_Vx770",
  "A_VX809comb",
  "liver_disease"
)
# Nice labels for plots and tables
labels <- list(
  cfrd_status_annual = "CFRD Status",
  MutClass = "Mutation class",
  Race = "Race",
  Hispanicrace = "Hispanic",
  Gender = "Sex",
  A_IsOnEnzymes = "Pancreatic enzyme use",
  ppFEV1_cat = "FEV1 percent predicted category",
  A_FEV1_pct_predicted = "FEV1 percent predicted",
  A_FVC_pct_predicted = "FVC percent predicted",
  tube_feeding = "Enteric feedings",
  liver_disease = "Liver disease",
  A_corticosteroids1 = "Use of corticosteroids",
  NumPulmExacerbation = "Admissions for PEx",
  age_group = "Age group",
  height_perc = "Height percentile",
  A_Vx770 = "Use of CFTR modulator Vx770",
  A_VX809comb = "Use of CFTR modulator Vx809 combination",
  A_pseudomonasaeruginosa = "Pseudomonas aeruginosa",
  A_fungalyeast1 = "Aspergillus (any species)",
  A_mycocultureresults3 = "Microorganisms in myco culture",
  A_cultureresults3 = "Microorganisms in culture",
  eDWID = "ID",
  tstart = "Interval start",
  tstop = "Interval stop",
  Age_YrEnd = "Age",
  cfrd_treatment = "Prescribed treatment for CFRD",
  cfrd_treatment_options1 = "Dietary change used to treat CFRD during the year",
  cfrd_treatment_options2 = "Oral hypoglycemic agents used to treat CFRD during the year",
  cfrd_treatment_options3 = "Intermittent insulin used to treat CFRD during the year",
  cfrd_treatment_options4 = "Chronic insulin used to treat CFRD during the year",
  years_with_data = "Years With Data"
)
label(annual[, which(colnames(annual) %in% names(labels))]) <-
  labels[colnames(annual)[which(colnames(annual) %in% names(labels))]]
# Per reviewer, out of X individuals with a diagnosis of CFRD, X number had an
# OGTT (and X had an A1c, but no OGTT) that year or the year prior.
# This is super slow but idc idc
cfrd_only <- apply(first_cfrd, 1, function(r) {
  id <- as.numeric(r["eDWID"])
  year <- as.numeric(r["first_cfrd"])
  d <- annual[annual$eDWID == id & annual$ReviewYear %in% c(year, year - 1), ]
  a1c <- as.numeric(last(d["A_hgba1c"], na_rm = TRUE))
  ogtt0hr <- as.numeric(last(d["A_ogttfast_bloodglucose"], na_rm = TRUE))
  ogtt2hr <- as.numeric(last(d["A_twohour_bloodglucose"], na_rm = TRUE))
  return(c(id, year, a1c, ogtt0hr, ogtt2hr))
})
cfrd_only <- data.frame(t(cfrd_only))
colnames(cfrd_only) <- c("id", "year", "a1c", "ogtt0hr", "ogtt2hr")
cfrd_only <- left_join(
  cfrd_only,
  annual |> mutate(eDWID = as.numeric(eDWID)),
  by = join_by(id == eDWID, year == ReviewYear)
)
cfrd_only$a1c_ogtt <- apply(cfrd_only, 1, function(r) {
  not_missing <- paste(
    which(!is.na(r[c("a1c", "ogtt0hr", "ogtt2hr")])),
    collapse = "_"
  )
  return(not_missing)
})
cfrd_only$a1c_ogtt <- factor(
  cfrd_only$a1c_ogtt,
  levels = c("", "1", "1_2", "1_2_3", "1_3", "2", "2_3", "3"),
  labels = c(
    "Neither",
    "HbA1c Only",
    "OGTT",
    "OGTT",
    "OGTT",
    "OGTT",
    "OGTT",
    "OGTT"
  )
)
cfrd_only |>
  select(
    a1c_ogtt,
    Age_YrEnd,
    A_weight,
    A_height,
    bmi_adult,
    bmi_perc,
    bmi_cat,
    A_FEV1_pct_predicted,
    A_FVC_pct_predicted,
    Race,
    Hispanicrace,
    MutClass,
    a1c,
    A_ogttfast_bloodglucose,
    A_twohour_bloodglucose,
    A_IsOnEnzymes,
    liver_disease,
    A_pseudomonasaeruginosa,
    A_fungalyeast1,
    A_mycocultureresults3,
    A_cultureresults3,
    cfrd_treatment,
    cfrd_treatment_options1,
    cfrd_treatment_options2,
    cfrd_treatment_options3,
    cfrd_treatment_options4,
    years_with_data
  ) |>
  tbl_summary(
    by = a1c_ogtt,
    missing_text = "Missing",
    statistic = list(all_continuous() ~ "{mean} ({sd})")
  ) |>
  add_overall() |>
  add_p(
    test = list(
      all_continuous() ~ "oneway.test",
      "years_with_data" ~ "kruskal.test"
    )
  ) |>
  modify_caption("**All Groups**")
cfrd_only |>
  filter(a1c_ogtt %in% c("OGTT", "HbA1c Only")) |>
  mutate(a1c_ogtt = droplevels(a1c_ogtt)) |>
  select(
    a1c_ogtt,
    Age_YrEnd,
    A_weight,
    A_height,
    A_bmivalue,
    A_bmipercentile,
    A_FEV1_pct_predicted,
    A_FVC_pct_predicted,
    Race,
    Hispanicrace,
    MutClass,
    a1c,
    A_ogttfast_bloodglucose,
    A_twohour_bloodglucose,
    A_IsOnEnzymes,
    liver_disease,
    A_pseudomonasaeruginosa,
    A_fungalyeast1,
    A_mycocultureresults3,
    A_cultureresults3,
    cfrd_treatment,
    cfrd_treatment_options1,
    cfrd_treatment_options2,
    cfrd_treatment_options3,
    cfrd_treatment_options4,
    years_with_data
  ) |>
  tbl_summary(
    by = a1c_ogtt,
    missing_text = "Missing",
    statistic = list(all_continuous() ~ "{mean} ({sd})")
  ) |>
  add_overall() |>
  add_p(test = list(all_continuous() ~ "oneway.test")) |>
  modify_caption("**OGTT vs. HbA1c Only**")
```

## FEV1 trends by diagnosis method

### LOESS-smoothed plot

```{r}
#| warning: false
#| message: false
# Plot by diagnosis type
mod_df = cfrd_only |>
  select(id, a1c_ogtt, Age_YrEnd) |>
  rename(eDWID = id)
mod_df = left_join(
  annual |> select(-Age_YrEnd) |> mutate(eDWID = as.numeric(eDWID)),
  mod_df,
  by = join_by(eDWID)
)
mod_df = mod_df |>
  drop_na(first_cfrd) |>
  group_by(eDWID) |>
  mutate(years_to_cfrd = ReviewYear - first_cfrd)
var_label(mod_df$years_to_cfrd) = "Years to CFRD"
var_label(mod_df$Age_YrEnd) = "Age at Diagnosis"
ggplot(
  mod_df |> filter(!is.na(a1c_ogtt)),
  aes(
    y = A_FEV1_pct_predicted,
    x = years_to_cfrd,
    color = a1c_ogtt,
    group = a1c_ogtt
  )
) +
  xlab("Years from CFRD") +
  xlim(c(-5, 5)) +
  geom_point(alpha = 0.1, shape = ".") +
  geom_smooth(formula = y ~ s(x, bs = "cr")) +
  theme_bw() +
  theme(legend.title = element_blank())
```

### Piecewise linear model results

```{r}
# Fit model - adjust for age at dx, sex, genotype (severe vs mild), pancreatic
# insufficiency, age at CF diagnosis (do we know this?), number of clinic
# visits/year, use of CFTR modulators
mod_df$x = mod_df$years_to_cfrd * (mod_df$years_to_cfrd >= 0)
label(mod_df$x) = "Change in Slope Post-CFRD"
label(mod_df$years_to_cfrd) = "Slope Pre-CFRD"
label(mod_df$a1c_ogtt) = "Diagnosis Method"
label(mod_df$Age_YrEnd) = "Age at Diagnosis"
# Write data so Christine can see missing data
t = mod_df |>
  select(
    eDWID,
    years_to_cfrd,
    A_FEV1_pct_predicted,
    A_FVC_pct_predicted,
    a1c_ogtt,
    Age_YrEnd,
    Gender,
    MutClass,
    A_IsOnEnzymes,
    A_Vx770,
    A_VX809comb,
    cfrd_treatment,
    cfrd_treatment_options1,
    cfrd_treatment_options2,
    cfrd_treatment_options3,
    cfrd_treatment_options4
  ) |>
  drop_na(A_FEV1_pct_predicted)
write.csv(t, "./Data_Clean/fev1_model_data.csv", row.names = F, na = "")
# Fit the model
m <- lmer(
  A_FEV1_pct_predicted ~ years_to_cfrd *
    a1c_ogtt +
    x * a1c_ogtt +
    Age_YrEnd +
    Gender +
    MutClass +
    A_IsOnEnzymes +
    A_Vx770 +
    A_VX809comb +
    (1 | eDWID),
  data = mod_df
)
# Population-averaged plot
pop_dat <- data.frame(expand.grid(
  years_to_cfrd = -5:5,
  a1c_ogtt = unique(mod_df$a1c_ogtt),
  Age_YrEnd = mean(mod_df$Age_YrEnd, na.rm = T),
  Gender = "M",
  MutClass = "1-3",
  A_IsOnEnzymes = "Yes",
  A_Vx770 = "No",
  A_VX809comb = "No"
))
pop_dat$x <- (pop_dat$years_to_cfrd >= 0) * pop_dat$years_to_cfrd
pred <- predict(m, re.form = NA, newdata = pop_dat, se.fit = T)
pop_dat$pred <- pred$fit
pop_dat$ll <- pop_dat$pred - (1.96 * pred$se.fit)
pop_dat$ul <- pop_dat$pred + (1.96 * pred$se.fit)
ggplot(
  pop_dat,
  aes(x = years_to_cfrd, y = pred, group = a1c_ogtt, colour = a1c_ogtt)
) +
  geom_point() +
  geom_errorbar(aes(ymin = ll, ymax = ul), width = 0.1) +
  geom_line() +
  xlab("Years from CFRD") +
  ylab("FEV1 % Predicted") +
  theme_classic(base_size = 15)
# Contrasts
neither_pre <- rep(0, nrow(summary(m)$coefficients))
neither_change <- rep(0, nrow(summary(m)$coefficients))
neither_pre[which(rownames(summary(m)$coefficients) == "years_to_cfrd")] = 1
neither_change[which(rownames(summary(m)$coefficients) == "x")] = 1
a1c_pre <- rep(0, nrow(summary(m)$coefficients))
a1c_change <- rep(0, nrow(summary(m)$coefficients))
a1c_pre[which(
  rownames(summary(m)$coefficients) %in%
    c("years_to_cfrd", "years_to_cfrd:a1c_ogttHbA1c Only")
)] = 1
a1c_change[which(
  rownames(summary(m)$coefficients) %in%
    c("x", "a1c_ogttHbA1c Only:x")
)] = 1
ogtt_pre <- rep(0, nrow(summary(m)$coefficients))
ogtt_change <- rep(0, nrow(summary(m)$coefficients))
ogtt_pre[which(
  rownames(summary(m)$coefficients) %in%
    c("years_to_cfrd", "years_to_cfrd:a1c_ogttOGTT")
)] = 1
ogtt_change[which(
  rownames(summary(m)$coefficients) %in%
    c("x", "a1c_ogttOGTT:x")
)] = 1
contr <- rbind(
  "HbA1c Only Pre-CFRD" = a1c_pre,
  "HbA1c Only Post-CFRD" = a1c_pre + a1c_change,
  "OGTT Pre-CFRD" = ogtt_pre,
  "OGTT Post-CFRD" = ogtt_pre + ogtt_change,
  "Neither Pre-CFRD" = neither_pre,
  "Neither Post-CFRD" = neither_pre + neither_change
)
change_mod_slopes <- glht(m, linfct = contr)
change_mod_slopes_ci <- confint(change_mod_slopes, calpha = univariate_calpha())
change_mod_slopes_ci$confint |>
  as.data.frame() |>
  gt(caption = "Slopes by Diagnosis Method", rownames_to_stub = T) |>
  fmt_number(decimals = 2)
# Model table
m |> tbl_regression() |> add_n(location = "level")
```

### Categorical model results

## FVC trends by diagnosis method

### LOESS-smoothed plot

```{r} 
ggplot(
  mod_df |> filter(!is.na(a1c_ogtt)),
  aes(
    y = A_FVC_pct_predicted,
    x = years_to_cfrd,
    color = a1c_ogtt,
    group = a1c_ogtt
  )
) +
  xlab("Years from CFRD") +
  xlim(c(-5, 5)) +
  geom_point(alpha = 0.1, shape = ".") +
  geom_smooth(formula = y ~ s(x, bs = "cr")) +
  theme_bw() +
  theme(legend.title = element_blank())
```

### Piecewise linear model results

```{r}
# Fit model - adjust for age at dx, sex, genotype (severe vs mild), pancreatic
# insufficiency, age at CF diagnosis (do we know this?), number of clinic
# visits/year, use of CFTR modulators
mod_df$x = mod_df$years_to_cfrd * (mod_df$years_to_cfrd >= 0)
label(mod_df$x) = "Change in Slope Post-CFRD"
label(mod_df$years_to_cfrd) = "Slope Pre-CFRD"
label(mod_df$a1c_ogtt) = "Diagnosis Method"
label(mod_df$Age_YrEnd) = "Age at Diagnosis"
m <- lmer(
  A_FVC_pct_predicted ~ years_to_cfrd *
    a1c_ogtt +
    x * a1c_ogtt +
    Age_YrEnd +
    Gender +
    MutClass +
    A_IsOnEnzymes +
    A_Vx770 +
    A_VX809comb +
    (1 | eDWID),
  data = mod_df
)
# Population-averaged plot
pop_dat <- data.frame(expand.grid(
  years_to_cfrd = -5:5,
  a1c_ogtt = unique(mod_df$a1c_ogtt),
  Age_YrEnd = mean(mod_df$Age_YrEnd, na.rm = T),
  Gender = "M",
  MutClass = "1-3",
  A_IsOnEnzymes = "Yes",
  A_Vx770 = "No",
  A_VX809comb = "No"
))
pop_dat$x <- (pop_dat$years_to_cfrd >= 0) * pop_dat$years_to_cfrd
pred <- predict(m, re.form = NA, newdata = pop_dat, se.fit = T)
pop_dat$pred <- pred$fit
pop_dat$ll <- pop_dat$pred - (1.96 * pred$se.fit)
pop_dat$ul <- pop_dat$pred + (1.96 * pred$se.fit)
ggplot(
  pop_dat,
  aes(x = years_to_cfrd, y = pred, group = a1c_ogtt, colour = a1c_ogtt)
) +
  geom_point() +
  geom_errorbar(aes(ymin = ll, ymax = ul), width = 0.1) +
  geom_line() +
  xlab("Years from CFRD") +
  ylab("FVC % Predicted") +
  theme_classic(base_size = 15)
# Contrasts
neither_pre <- rep(0, nrow(summary(m)$coefficients))
neither_change <- rep(0, nrow(summary(m)$coefficients))
neither_pre[which(rownames(summary(m)$coefficients) == "years_to_cfrd")] = 1
neither_change[which(rownames(summary(m)$coefficients) == "x")] = 1
a1c_pre <- rep(0, nrow(summary(m)$coefficients))
a1c_change <- rep(0, nrow(summary(m)$coefficients))
a1c_pre[which(
  rownames(summary(m)$coefficients) %in%
    c("years_to_cfrd", "years_to_cfrd:a1c_ogttHbA1c Only")
)] = 1
a1c_change[which(
  rownames(summary(m)$coefficients) %in%
    c("x", "a1c_ogttHbA1c Only:x")
)] = 1
ogtt_pre <- rep(0, nrow(summary(m)$coefficients))
ogtt_change <- rep(0, nrow(summary(m)$coefficients))
ogtt_pre[which(
  rownames(summary(m)$coefficients) %in%
    c("years_to_cfrd", "years_to_cfrd:a1c_ogttOGTT")
)] = 1
ogtt_change[which(
  rownames(summary(m)$coefficients) %in%
    c("x", "a1c_ogttOGTT:x")
)] = 1
contr <- rbind(
  "HbA1c Only Pre-CFRD" = a1c_pre,
  "HbA1c Only Post-CFRD" = a1c_pre + a1c_change,
  "OGTT Pre-CFRD" = ogtt_pre,
  "OGTT Post-CFRD" = ogtt_pre + ogtt_change,
  "Neither Pre-CFRD" = neither_pre,
  "Neither Post-CFRD" = neither_pre + neither_change
)
change_mod_slopes <- glht(m, linfct = contr)
change_mod_slopes_ci <- confint(change_mod_slopes, calpha = univariate_calpha())
change_mod_slopes_ci$confint |>
  as.data.frame() |>
  gt(caption = "Slopes by Diagnosis Method", rownames_to_stub = T) |>
  fmt_number(decimals = 2)
# Model table
m |> tbl_regression() |> add_n(location = "level")
```