---
title: "20200224_Table1_Final"
author: "Casey Sakamoto"
date: "2/24/2020"
output:
  pdf_document: default
  word_document: default
---
This is final version (instead of 20200101_table1.r)
(i messed up on version control)

```{r setup, include=FALSE}
#setwd("C:/Users/Casey/Desktop/research")
library(tidyverse)
library(tableone)
library(readxl)
library(knitr)
outpatient2020_01_25 <- read.csv("/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Vigers/CF/Jordan Hoppe/PEX Microbiome/Data_Raw/outpatient2020_01_25.csv")
cult3 <- read_excel("/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Vigers/CF/Jordan Hoppe/PEX Microbiome/Data_Raw/cult3.xlsx")
#outpatient2020_01_25 <- read.csv("C:/Users/Casey/Desktop/research/20200128plots/outpatient2020_01_25.csv")
#cult3 <- read_excel("C:/Users/Casey/Desktop/research/cult3.xlsx")
# age, gender, base fev1% (m r), fev1 pred(mr)
# change pred fev (mr), v1 pes score, days between visit (mr)
# ? genotyp, cf resp culture v1, positie viral pcr
# antibiotic class prescribed
outpatient_main = outpatient2020_01_25 %>% 
  select(sid,molecularid, perc_total, last, visit, lq_all, fev1_perc_6m_prior,sex , pes_total, age_yrs,
         fev1_perc_pre, fev1_perc_post,Antibiotic_class, visit_dif,pcr_neg, genotype1,genotype2, ShannonH_Median )%>%
  filter(!(sid == "JAR018" | sid == "BAR019" | sid == "NAO032" | sid == "EIL010" ))

outpatient_2vv = outpatient_main %>% group_by(sid,visit) %>% filter(n() > 224)
# take the max lq_all
outpatient_2vv = outpatient_2vv %>% group_by(sid, visit) %>% filter(lq_all == max(lq_all))

# combine this with our other patient data
tempdf = outpatient_main %>% group_by(sid,visit) %>% filter(n() <= 224)
outpatient_2vv = rbind(tempdf, outpatient_2vv)
rm(tempdf)
# subjects not in our 19
sublist = c("BAM014", "BSN024", "ESP008", "MEB022", "NDR020", "SKH012", "VAC001", "VCR009", "A_MO25")
outpatient_2vv = outpatient_2vv %>%  filter(!(sid %in% sublist))

summary(outpatient_2vv)

outpatient_2vv = outpatient_2vv %>% mutate(
  genotype = case_when(genotype1 == "F508del" & genotype2 == "F508del" ~ "F508del/F508del",
                       genotype1 == "F508del" & genotype2 != "F508del" ~ "F508del/Other",
                       visit==1 & sid =="SLP006"~"Other"))
# observations for table 1
unique_df = outpatient_2vv %>% select(-c(last, perc_total)) %>% unique.data.frame()
# sid and mid
molecular_id = unique_df[,1:2]
#write.csv(molecular_id, "molecularid.csv")
#
df_v1 = unique_df %>% filter(visit==1) %>% select(-visit_dif, -visit)
df_v2 = unique_df %>% filter(visit==2) 
df_v2 = df_v2 %>%  select(sid, visit_dif)

patient_t1_df = full_join(df_v1, df_v2, by = 'sid')
patient_t1_df = patient_t1_df %>% select(-visit.x, -visit.y)
rm(df_v1, df_v2, unique_df)
patient_t1_df = patient_t1_df %>% mutate(change_fev_perc = fev1_perc_pre - fev1_perc_6m_prior,
                                         change_fev_perc_v1v2 = fev1_perc_post - fev1_perc_pre)
patient_t1_df$age_yrs = floor(patient_t1_df$age_yrs)
# create table 1
all_var = c("age_yrs", "sex","genotype", "fev1_perc_6m_prior", "fev1_perc_pre", "change_fev_perc", "pes_total", "Antibiotic_class", "visit_dif","ShannonH_Median" ,"pcr_neg")
med_iqr_vars = c("age_yrs", "fev1_perc_6m_prior","fev1_perc_pre", "ShannonH_Median","change_fev_perc", "pes_total", "visit_dif")
cat_vars = c("sex","genotype", "antibiotic_class","pcr_neg")
t1 = CreateTableOne(data = patient_t1_df, vars = all_var, factorVars = cat_vars)
final = print(t1, nonnormal = med_iqr_vars, showAllLevels = TRUE, minMax = TRUE)

#write.csv(final, "table1.csv")
```

```{r table1 kable, echo=FALSE}
# names for rows in table order
t1_rownames = c("n",
                "Age in Years median[range]",
                "Sex n(%)",
                " ",
                "Genotype n(%)",
                " ",
                " ",
                "Baseline $FEV_1$% (highest predicted in prior 6 months) median[range]",
                "$FEV_1$% Predicted at Visit 1 median[range]",
                "Change in $FEV_1$% predicted from baseline to visit 1 median[range]",
                "Visit 1 PES Score median[range]",
                "Antibiotic Class n(%)",
                " ",
                " ",
                " ",
                " ",
                "Days Between Visits median[range]",
                "Shannon's H median[range]",
                "Positive Viral PCR at Visit 1 n(%)",
                " "
                )
t1_colnames = c("",
                "n = 19")
colnames(final) = t1_colnames
rownames(final) = t1_rownames
# remove bottom row (20), (19,2)
# change sex 1=male 2=female
final = final[-20,]
final[19,1] = ""
final[3,1] = "Male"
final[4,1] = "Female"
kable(final[-1,], caption = "Patient Characteristics at Baseline and PEx")
```

```{r misc hypothesis tests, include=FALSE}

# looking at lq_all
unique_df = outpatient_2vv %>% select(-c(last, perc_total)) %>% unique.data.frame()
df_v1 = unique_df %>% filter(visit==1) %>% select(-visit_dif, -visit)
df_v2 = unique_df %>% filter(visit==2) 

df_v1 = df_v1 %>% select(sid, lq_all)
df_v2 = df_v2 %>% select(sid, lq_all)
load_df = full_join(df_v1,df_v2,by='sid') # x is visit 1, y is v2
load_df = load_df %>% select(sid, lq_all.x, lq_all.y) %>% mutate(dif = lq_all.y - lq_all.x)
mean(load_df$dif); sd(load_df$dif)
hist(df_v1$lq_all)
hist(df_v2$lq_all)

# wilcoxon signed rank test
wilcox.test(df_v1$lq_all, df_v2$lq_all, paired = TRUE)
# 

rm(df_v1,df_v2,unique_df)
setwd("C:/Users/Casey/Desktop/WorkData/Microbiome Brandie 2019-2020")
write.csv(patient_t1_df, "patient_t1_df.csv")
```


