---
title: "SSwAB-IT Phase 1 Analysis"
author: "Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
    theme:
      light: flatly
      dark: darkly
bibliography: /Users/timvigers/Dropbox/Miscellaneous/zotero.bib
csl: /Users/timvigers/Dropbox/Miscellaneous/american-medical-association.csl
editor: source
---

```{r setup}
#| include: false
library(tidyverse)
library(gtsummary)
library(redcapAPI)
home_dir <- switch(Sys.info()["sysname"],
  "Darwin" = "/Users/timvigers/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Vigers/CF",
  "Windows" = "C:/Users/timvigers/OneDrive - The University of Colorado Denver/Vigers/CF"
)
knitr::opts_knit$set(root.dir = home_dir)
```

```{r data cleaning}
#| include: false
# Import from REDCap
unlockREDCap(c(rcon = "SSwAB-IT (New)"),
  keyring = "API_KEYs",
  envir = 1,
  url = "https://redcap.ucdenver.edu/api/"
)
exportBulkRecords(list(db = rcon), envir = 1)
```

# Feasibility

```{r}
#| message: false
db_feasibility %>%
  select(
    redcap_data_access_group, able_to_collect_sample,
    believe_collected_good_sample, sample_difficulty, willing_to_repeat,
  ) %>%
  tbl_summary(by = redcap_data_access_group, missing_text = "Missing") %>%
  add_overall()
```
