---
title: "Quantifying Sweat Chloride in CF Carriers"
author: "Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
editor: source
---

```{r setup}
#| include: false
library(redcapAPI)
library(tidyverse)
library(arsenal)
github_dir <- switch(Sys.info()["sysname"],
  "Darwin" = "/Users/timvigers/GitHub",
  "Windows" = "C:/Users/timvigers/GitHub",
  "Linux" = "/home/timvigers/GitHub"
)
home_dir <- switch(Sys.info()["sysname"],
  "Darwin" = "/Users/timvigers/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Vigers/CF/Angela Metcalf/Quantifying Sweat Chloride in CF Carriers",
  "Linux" = "/home/timvigers/OneDrive/Vigers/CF/Angela Metcalf/Quantifying Sweat Chloride in CF Carriers"
)
knitr::opts_knit$set(root.dir = home_dir)
```

```{r data cleaning}
#| message: false
#| warning: false
# Import from REDCap
unlockREDCap(c(rcon = "Sweat Electrolytes in CF Carriers 24-0691"),
  keyring = "API_KEYs",
  envir = 1,
  url = "https://redcap.ucdenver.edu/api/"
)
df <- exportRecordsTyped(rcon)
# Format
df <- df %>%
  mutate(
    `Cl Right` = as.numeric(cl_right), `Cl Left` = as.numeric(cl_left),
    `Na Right` = as.numeric(na_right), `Na Left` = as.numeric(na_left)
  )
df$`Mean Cl` <- rowMeans(df[, c("Cl Right", "Cl Left")], na.rm = T)
df$`Mean Na` <- rowMeans(df[, c("Na Right", "Na Left")], na.rm = T)
df$Ratio <- df$`Mean Na` / df$`Mean Cl`
# Per Angela, exclude some participants
df <- df[!df$pid %in% c(15, 36), ]
```

# NACFC 2025

```{r results='asis'}
interim <- read.csv("./Data_Clean/Interim reduced data set.csv")
interim$`Chloride >= 30`=interim$Chloride >= 30
summary(tableby(
  Carrier ~ kwt(Average.sodium, "medianq1q3", "iqr") +
    kwt(Chloride, "medianq1q3", "iqr") + kwt(Ratio, "medianq1q3", "iqr") +
    `Chloride >= 30`,
  data = interim
), pfootnote = T)
```

# Confidence interval power calculations

```{r}
ns <- 35:45
sigma <- round(sd(df$`Mean Cl`, na.rm = T), 1)
power <- lapply(ns, function(n) {
  se <- qt(0.05 / 2, lower.tail = F, df = n - 1) * (sigma / sqrt(n))
  return(c(
    "Confidence level" = 0.95, "Sample size (N)" = n,
    "Actual Distance from Mean to Limits" = se,
    "Standard deviation of sweat chloride" = sigma
  ))
})
power <- do.call(rbind, power)
knitr::kable(power)
```
